README.md
A tip to check the resources created by a deployment
=> Add a way to search the resouces of a particular deployment

rakefiles/kops.rake
Latest AWS CLI version does not output json by default.
=> Fixes for destroy task

gcp/README.md, gcp/docker-compose.yaml
Update README for this change and some notes from Alfredo's experience trying to
use the official account.
=> Use gpii/exekube image.

CI-CD.md, aws/README.md
This work was motivated by https://issues.gpii.net/browse/GPII-3103 but includes a number of cleanups based on Cindy's feedback while working with gpii-infra, plus some other edits and updates.
Reading raw markdown is no fun, so here's the rendered version:
https://github.com/mrtyler/gpii-infra/blob/GPII-3103-readme/aws/README.md
=> GPII-3103 README improvements.

gcp/modules/couchdb/main.tf
We are also missing persistent volumes, will create separate PR for that.
=> GPII-2960: Fix for couchdb module to execute finish_cluster action after chart install

gcp/rakefiles/entrypoint.rake
I am not sure if entrypoint is the correct place to create missing dirs, but this interferes with my changes from #44 and will most likely change after it is merged, so I just want current master fixed.
=> Small fixes for GCP part

gcp/rakefiles/entrypoint.rake
=> Rake xk should default into xk[sh]

.gitlab-ci.yml, aws/rakefiles/vars.rb
I haven't tested the gitlab-ci.yml change. One way or another that will involve running through CI, so maybe just merge this and find out if it works and if not I can revert or correct in a follow-up.
=> GPII-3199: guard rail for running in prd

aws/README.md
See ticket for some additional context and justification for doing this in documentation instead of code :).
=> GPII-3200: Add one-time manual setup instructions for Route 53 Health Checks

common/charts/couchdb/Chart.yaml, common/charts/couchdb/README.md, common/charts/couchdb/templates/statefulset.yaml, common/charts/couchdb/values.yaml, gcp/modules/templater/values/couchdb.yaml
This solves the problem perfectly.
Chart changes should go to the https://github.com/helm/charts I guess?
=> [GPII-3195]: Add affinity setting to CouchDB

aws/README.md
Here's the promised small "how to" process made for this August demo.
Let me know if you have any comments.
=> Documented the process of loading data into a running preferences server

.gitlab-ci.yml
From https://github.com/gpii-ops/gpii-infra/pull/92#discussion_r211444771
=> GPII-2996: Sergey suggests cleaning secrets harder.

README.md, aws/README.md, gcp/README.md
Rendered markdown: https://github.com/mrtyler/gpii-infra/tree/authy-pushdown
=> README: authy, design principles, top-level

.gitlab-ci.yml
To prevent failures like:
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/93807657
=> Destroy locust tfstate in gcp-dev

.gitlab-ci.yml
Fix the .gitlab-ci.yml while the merge of GPII-3125
=> Fix tests path

shared/rakefiles/test.rake
Take 2. We apparently modified the wrong value here.
=> GPII-3250: We need to change the max response time instead of the median

shared/rakefiles/test.rake
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/101510080
=> Bump preferences MRT to 2000

common/live/prd/infra/dev/sgithens/terraform.tfvars
This creates the infrastructure needed for Steve Githens
=> Add sgithens as a dev user

gcp/modules/gcp-stackdriver-exclusion/main.tf
In my excitement to merge #114, I forgot to do this update that @natarajaya  told me I would need.
=> GPII-3327: Update to Beta Stackdriver names.

common/live/prd/infra/dev/alfredo/terraform.tfvars, common/live/prd/infra/dev/gitlab-runner/terraform.tfvars, common/live/prd/infra/dev/jhernandez/terraform.tfvars, common/live/prd/infra/dev/natarajaya/terraform.tfvars, common/live/prd/infra/dev/sergio/terraform.tfvars, common/live/prd/infra/dev/sgithens/terraform.tfvars, common/live/prd/infra/dev/stepan/terraform.tfvars, common/live/prd/infra/dev/tyler/terraform.tfvars, common/live/prd/infra/dev/zone/terraform.tfvars, common/live/prd/infra/prd/zone/terraform.tfvars, common/live/prd/infra/stg/zone/terraform.tfvars, common/live/stg/infra/dev/doe/terraform.tfvars, common/live/stg/infra/dev/zone/terraform.tfvars, common/live/stg/infra/prd/zone/terraform.tfvars, common/live/stg/infra/stg/zone/terraform.tfvars, common/modules/gcp-project/main.tf
This PR has the code to set the owner from the `project_owner` variable.
=> GPII-3405 Add project_owner to the project

.gitlab-ci.yml, aws/modules/k8s-cluster-dns/main.tf, aws/modules/k8s-cluster-dns/provider.tf, aws/modules/volume/main.tf, aws/modules/volume/provider.tf, common/modules/aws-gcp-dns/aws-dns-zone/main.tf, common/modules/aws-gcp-dns/gcp-dns-zone/main.tf, common/modules/aws-gcp-dns/main.tf, common/modules/gcp-project/main.tf, gcp/modules/couchdb/main.tf, gcp/modules/gcp-stackdriver-exclusion/main.tf, gcp/modules/gke-cluster/main.tf, gcp/modules/gpii-flowmanager/main.tf, gcp/modules/gpii-preferences/main.tf
As we don't seem to be very good at running `terraform fmt` before comitting code, I propose to add this step to our CI pipeline.
It will be annoying at first, and everyone will hate me for this :), but life is hard.
**update:** We even already have ticket for this [GPII-3334](https://issues.gpii.net/browse/GPII-3334)
=> GPII-3334: Add terraform fmt check to pipeline

gcp/README.md
This PR adds some notes that can help to the developers in the use of the new infrastructure built on top of GCP.
[Rendered README.md](https://github.com/amatas/gpii-infra/blob/GPII-3412/gcp/README.md)
=> GPII-3412 - Improve the GCP/README.md

.gitlab-ci.yml
Also added a Tag to Stepan's new linting job, as mentioned in https://github.com/gpii-ops/gpii-infra/pull/164#issuecomment-427950427
=> GPII-3355: Ignore failures in after_scripts.

.gitlab-ci.yml, shared/rakefiles/entrypoint.rake
Adds a small report at the end of the deploy command.
*Extra: task to update the exekube Docker image*
If you think that other kind of information could be useful in this report, please add it in to the comments.
=> GPII-3413 - Add report of the status of the GCP cluster at the end of the deploy command

gcp/modules/locust/client.rb, gcp/modules/locust/main.tf, gcp/modules/locust/swarm.tf, gcp/modules/locust/variables.tf, shared/rakefiles/test.rake
This is how results look like in [Stackdriver Dashboard](https://app.google.stackdriver.com/dashboards/10687553252455564757?project=gpii-gcp-dev-natarajaya).
Only totals are being posted now, I think this should be pretty helpful already.
Should we post distributions too?
=> [GPII-3473]: Post Locust stats to Stackdriver

gcp/README.md, gcp/live/dev/k8s/stackdriver/alerting/terraform.tfvars, gcp/live/prd/k8s/stackdriver/alerting/terraform.tfvars, gcp/live/stg/k8s/stackdriver/alerting/terraform.tfvars, gcp/modules/gcp-stackdriver-alerting/client.rb, gcp/modules/gcp-stackdriver-alerting/main.tf, gcp/modules/gcp-stackdriver-alerting/resources/alert_policies/cluster_resource_allocatable_utilization.json, gcp/modules/gcp-stackdriver-alerting/resources/uptime_checks/preferences.json, gcp/modules/locust/swarm.tf, gcp/modules/locust/variables.tf
* Fix for Preferences Uptime check to use HTTPS for staging and prod
* Fix for issue with `STACKDRIVER_DEBUG` 
* Change "Node Resource Allocatable Utilization" to "Cluster Resource Allocatable Utilization" policy
* Added readme sections to configure Stackdriver Workspace and Dashboards.
=> [GPII-2967]: Various fixes related to monitoring and alerting

common/modules/gcp-project/main.tf
=> Add roles/monitoring.editor role to the SA

gcp/modules/gcp-stackdriver-alerting/main.tf
@stepanstipl This is the best remedy I could offer for `Deadline expired before operation could complete.` issues.
=> [GPII-3505]: Add retry loop to stackdriver-alerting module resources

common/modules/gcp-project/main.tf, shared/rakefiles/xk_infra.rake
=> GPII-3354 - Set proper common permissions at organization level

gcp/README.md
Per our Parking Lot discussion, I established a section in the README for recording this kind of thing.
=> GPII-3492: Start section on operational principles.

gcp/README.md
I also moved Troubleshooting section after Monitoring and updated headings order.
[Rendered view](https://github.com/natarajaya/gpii-infra/blob/7c4e5abddbff404e783dc00f5b38034f562b43fe/gcp/README.md).
=> [GPII-3495]: Update GCP readme with more troubleshooting hints

gcp/modules/couchdb/main.tf, gcp/modules/gcp-stackdriver-lbm/main.tf, gcp/modules/gcp-stackdriver-monitoring/main.tf, gcp/modules/locust/swarm.tf
This fixes second bug from:
https://issues.gpii.net/browse/GPII-3566
=> [GPII-3566]: Retry exactly RETRY_COUNT times

shared/rakefiles/ci.rake
Looks like I missed couple of things in #229.
=> [GPII-3325]: Fix CI rake tasks to handle SA key file properly

shared/rakefiles/xk_config.rake, shared/rakefiles/xk_infra.rake
Another little thing left behind in #229.
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/134926047
=> [GPII-3325]: Bring back :configure_current_project task

shared/rakefiles/xk_infra.rake
And hopefully last thing that I missed in #229.
=> [GPII-3325]: Fix :refresh_common_infra dependency

shared/rakefiles/xk_config.rake, shared/rakefiles/xk_infra.rake
This fixes issue revealed in:
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/134948261
=> [GPII-3325]: Fix some more dependency issues

shared/rakefiles/xk_infra.rake
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/134961569
=> [GPII-3325]: Fix :apply_infra, :destroy_infra dependencies

shared/rakefiles/xk_util.rake
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/134948261
=> [GPII-3325]: Fix :destroy_sa_keys dependencies

gcp/live/dev/k8s/stackdriver/monitoring/terraform.tfvars, gcp/modules/gcp-stackdriver-monitoring/main.tf, shared/rakefiles/xk_config.rake
We do not have auth user data in CI, and it is causing issues:
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/136974983
=> [GPII-3516]: Fix issues with auth_user_email and CI dev clusters

gcp/README.md
Adds a note about tracking issues we work on as per our standup discussion and action item
=> Add note about tracking issues we work on to README

.circleci/config.yml
https://circleci.com/gh/gpii-ops/gpii-infra/390?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> Pin down bundler version in CircleCI config

gcp/modules/couchdb/main.tf
Similar issue to https://github.com/gpii-ops/gpii-infra/pull/259.
=> [GPII-3647]: Fix retry logic in couchdb module shell code

gcp/README.md
Add note about Docker images we use. [Rendered](https://github.com/gpii-ops/gpii-infra/blob/52952d58814a5b323eab2aac611c8a830315a6e4/gcp/README.md#docker-images)
=> Note on Docker images

README.md, USER-TRAINING.md, common/live/prd/infra/dev/cindyli/terraform.tfvars, common/live/prd/infra/dev/clown/terraform.tfvars, common/live/prd/infra/dev/jj/terraform.tfvars, gcp/README.md
This resurrects https://github.com/gpii-ops/gpii-infra/pull/274, which was merged and then reverted in https://github.com/gpii-ops/gpii-infra/pull/291, and fixes a very silly bug (that Google did not help me find due to a very silly error message). Thanks Stepan!
=> GPII-3590: new users 2

gcp/modules/gke-cluster/main.tf
Based on [this comment](https://github.com/gpii-ops/gpii-infra/pull/199#issuecomment-463017515), Sergey tried this out while deploying https://github.com/gpii-ops/gpii-infra/pull/285 and found it worked. I did some more testing in my dev cluster.
=> Update instructions for cluster_protector.

gcp/README.md
Inspired by today's adventures with sgithens's tfstate bucket.
=> Add section on tfstate buckets.

shared/rakefiles/secrets.rb
This revealed that I needed to run 'rake grant_owner_role' to use 'rake sh' in stg.
=> GPII-3743: Improve error message and visibility.

gcp/README.md, gcp/modules/couchdb/recover.tf
Rendered markdown: https://github.com/mrtyler/gpii-infra/blob/gpii-3735-danger-zone/gcp/README.md#the-couchdb-cluster-wont-converge-because-one-of-its-disks-is-in-the-wrong-zone
=> GPII-3735: Add section on moving Disks to other Zones.

gcp/modules/gke-cluster/main.tf
This PR automates default GKE version detection and update to it.
Default (also called "stable" in GKE docs) is a version that GKE deploys by default and auto-upgrades masters to, therefore using default (as opposed to latest for example) should minimise the number of upgrades (and provide well-tested version).
PR also adds a safety check to prevent minor version upgrades (ie. `1.11` -> `1.12`).
Why check (and why via external data source):
- While terraform `google_container_engine_versions` data source supports version restriction via `version_prefix`, this does not apply to `default_cluster_version` (which kind of makes sense as there's only one default version) and therefore does not prevent minor version upgrades
- Unfortunately, as the version variable is dynamic, the simpler hack …
=> GPII-3790: Add default GKE version detection and update

gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/container_resource_limit_utilization.json
Full context in [GPII-3729](https://issues.gpii.net/browse/GPII-3766?focusedCommentId=37703&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-37703)
=> GPII-3729 - Remove memory utilization alert

shared/rakefiles/xk_config.rake
Add dependency on :configure, because this needs gcloud credentials etc.
=> Add some more output to fetch_helm_certs.

shared/rakefiles/secrets.rb, shared/rakefiles/tests/spec/secrets_spec.rb
Add some tests and a more specific error message.
=> GPII-3707: Fix a bug I introduced when adding @collected_secrets.

CONTACTING-OPS.md
These are some additions to the contacting ops doc, just to make easier the communication with us.
This PR can be improved with more details (how we can procedure with an issue, type of issues, etc) if we agreed in the next retro.
=> [NOJIRA] - Improve CONTACTING-OPS.md documentation

gcp/README.md
[Rendered markdown](https://github.com/mrtyler/gpii-infra/blob/gpii-3834-igqotw/gcp/README.md)
=> GPII-3834: 2019-03-18 stg incident follow-ups

gcp/modules/cert-manager/main.tf
=> GPII-3781: Add missing google provider definition #2

gcp/modules/gpii-flowmanager/main.tf, gcp/modules/gpii-preferences/main.tf
I've missed out the provider definition (again ;)
=> GPII-3841: Add missing provider definition

shared/versions.yml
Fix old locust docker image version.
=> Fix old locust version

shared/rakefiles/tests/spec/vars_spec.rb, shared/rakefiles/vars.rb, shared/versions.yml
See https://github.com/gpii-ops/gpii-version-updater/pull/13#issuecomment-483892637.
Must be deployed with https://github.com/gpii-ops/gpii-version-updater/pull/18.
=> GPII-3641: (gpii-infra) Restructure how upstream is specified.

shared/rakefiles/entrypoint_common.rake, shared/rakefiles/xk_infra.rake
Reverts gpii-ops/gpii-infra#366
=> Revert "[GPII-3865]: Improve the way we set organization-level permissions"

gcp/modules/couchdb/main.tf
Separated from https://github.com/gpii-ops/gpii-infra/pull/373.
=> GPII-3871: Re-forward port each time.

ONE-TIME-SETUP.md
Discovered this (and fixed access) while helping Joseph and Cindy access the cloud-developers@ archives.
=> Groups is now Groups For Business. /shrug.

gcp/modules/gpii-flowmanager/dns.tf
This is a roll-back for https://github.com/gpii-ops/gpii-infra/pull/324 till the issue with `istio-ingressgateway-certs` merged certs secret is investigated (https://issues.gpii.net/browse/GPII-3903)
=> Revert "Merge pull request #324 from stepanstipl/istio-phase3"

gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/cluster_resource_allocatable_utilization.json, gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/container_cpu_limit_utilization.json, gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/container_restart_rate.json, gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/couchdb_prometheus_exporter_exports_metric.json, gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/flowmanager_uptime.json, gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/k8s_snapshots_couchdb.json, gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/k8s_snapshots_errors.json, gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/pod_exec.json, gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/pod_volume_utilization.json
Once #404 is merged, duplicated commits should disappear and this will be easier to review.
=> [GPII-3942]:  Fix alert policy and condition naming

shared/versions.yml
See [GPII-3968](https://issues.gpii.net/browse/GPII-3968) for details.
=> GPII-3968: Updated universal version to pick up validation work.

common/live/prd/infra/dev/duhrer/terraform.tfvars
This PR creates a new dev environment (`dev-duhrer`) for Tony (`tony@`).
=> Create new dev env for Tony - dev-duhrer

gcp/docker-compose.yaml
Merge after https://github.com/gpii-ops/exekube/pull/57.
=> [GPII-3898]: New exekube with istioctl

gcp/README.md
[Rendered README](https://github.com/gpii-ops/gpii-infra/blob/e5273bdddd77961a66ff2e72cfa6cd4a9959ab73/gcp/README.md#working-with-couchdb-data).
=> [GPII-2805]: Update CouchDB restoration documentation

gcp/modules/gpii-flowmanager/dns.tf, gcp/modules/istio/main.tf
This PR addresses [GPII-3970](https://issues.gpii.net/browse/GPII-3970) and converts Istio's public IP to static one.
Changes:
- Move "wait for Istio" IP logic to istio module
- Convert Istio public IP to static one
=> Istio static ip

.circleci/config.yml, common/docker-compose.yaml, gcp/docker-compose.yaml
Merge after https://github.com/gpii-ops/exekube/pull/64
=> Use gpii/exekube:0.9.1-google_gpii.0

shared/rakefiles/entrypoint.rake, shared/rakefiles/xk.rake
This is a regression, introduced in https://github.com/gpii-ops/gpii-infra/pull/420/files#diff-e0a4c9132be9f827cd9f13dc69eaceedR72
String comparisons looks pretty ugly, but so is the way rake task arguments work.
=> [GPII-4058]: Fix sensitive data filtering

.gitlab-ci.yml
Reverts gpii-ops/gpii-infra#481
=> Revert "Fix gcp-unit-tests"

gcp/modules/istio/tracing.tf
This is 2nd try to fix Istio tracing rule race condition, part of [GPII-4085](https://issues.gpii.net/browse/GPII-4085).. Looks like the rules are created significantly later than rest of the resources:
```console
$ kubectl get rule -n istio-system stackdriver-tracing-rule
NAME                       AGE
stackdriver-tracing-rule   10m
$ kubectl get pods -n istio-system
NAME                                       READY   STATUS      RESTARTS   AGE
istio-citadel-77fd699689-j5pmp             1/1     Running     0          15m
istio-cleanup-secrets-1.1.12-hq5nn         0/1     Completed   0          15m
...
```
Perhaps this is related that CRDs are needed to be created first.
This PR adds wait specifically for the rule `stackdriver-tracing-rule`, instead of relying on the ingress-gateway IP.
=> GPII-4085: Fix Istio rule wait - 2nd try

gcp/modules/gke-cluster/main.tf
This PR fixes https://gitlab.com/gpii-ops/gpii-infra/-/jobs/289010827
=> [NOJIRA] Bump GKE version expected

ONE-TIME-SETUP.md, gcp/README.md
Rendered docs:
* https://github.com/mrtyler/gpii-infra/blob/gpii-2806-docs/ONE-TIME-SETUP.md
* https://github.com/mrtyler/gpii-infra/blob/gpii-2806-docs/gcp/README.md
=> GPII-2806 docs

shared/rakefiles/xk_util.rake
When reviewing changed assets, we had a problem to understand the very long output of the `rake display_scc_assets_changed` command. This PR makes the output easier to review - it removes all but basic info such as resource type and name, and groups output by type of change and type of resource.
_The `gcloud alpha scc assets list` output is quite difficult to work with, as the `stateChange` field is computed and can't be filtered on, therefore the necessity to use "more complex than I would like" `jq` function, instead of native `gcloud` formatting capabilities._
**New output:**
```json
{
"ADDED": {
"google.compute.Address": [
"istio-ingress"
],
"google.compute.Disk": [
"gke-k8s-cluster-terraform-20190319173-571935b8-99sf",
"gke-k8s-cluster-terraform-20190319173-a7b0c165-hmrv", …
```
=> Simplify `display_scc_assets_changed` output

common/modules/gcp-dns/gpii_net_records.tf
This PR fixes the CNAME data of some registries.
=> [GPII-2951] - Fix CNAMEs data

common/live/prd/infra/dev/sgrundell/terraform.tfvars
This PR adds common code to create dev env for Steve Grundell.
=> New dev env for Steve Grundell

common/modules/gcp-dns/gpii_net_records.tf
removes tabs and set the values to lowercase.
=> [NOJIRA] DNS - MX - Fix rrdata values

gcp/README.md
[Rendered README.](https://github.com/natarajaya/gpii-infra/blob/698be5a2eb07d342263bc5cc0c82bb80f91a76fb/gcp/README.md#flowmanger-module-has-been-deployed-successfully-but-kubectl--n-gpii-get-certificateissuer-still-says-that-no-resources-found)
=> Add note regarding ambiguous cert-manager CRDs

shared/versions.yml
See [GPII-4243](https://issues.gpii.net/browse/GPII-4243) for details.
=> GPII-4243: Deploy performant lower memory validation and remove context manager.

gcp/modules/gcp-stackdriver-export/gpii_key.tf
Previous cleanup step failed in CI:
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/387837004
=> [GPII-4158]: Set delete_contents_on_destroy flag for dev environments

gcp/README.md
This PR adds documentation for the situation when Istio components are failing to start because of internal certs being out of sync ([GPII-4298](https://issues.gpii.net/browse/GPII-4298)).
**Changes:**
- Add docs about Istio out of sync certificates
=> GPII-4298: Add docs about Istio out of sync certificates

common/modules/gcp-dns/gpii_net_records.tf
Request from Ben Caldwell in order to support mailgun provider
https://issues.gpii.net/browse/GPII-4299
=> GPII-4299: Add records for mailgun to be used by UL

shared/versions.yml
This pull updates universal to fix the issues with mouse settings reported by Amarja.  There is no data migration needed.
See [GPII-4342](https://issues.gpii.net/browse/GPII-4342) for more details.
=> GPII-4342: Update to universal container that fixes mouse settings.

gcp/live/prd/k8s/kube-system/backup-exporter/terraform.tfvars, gcp/live/stg/k8s/kube-system/backup-exporter/terraform.tfvars, gcp/modules/backup-exporter/alert_backup_exporter_errors.tf, gcp/modules/backup-exporter/alert_backup_exporter_snapshots.tf, gcp/modules/backup-exporter/main.tf
Fix this alert definition. Only PRD and STG are affected.
=> GPII-4328: Fix backup-exporter alerts definition

common/live/prd/infra/dev/chris/terraform.tfvars
New development environment for Chris.
=> New environment for Chris
