modules/deploy/52-couchdb-secrets.erb
modules/deploy/53-couchdb-statefulset.erb
modules/deploy/65-dataloader-job.erb
modules/deploy/73-preferences-deploy.erb
modules/deploy/Rakefile

This PR includes some refactoring of the code and also saves the variables in a yml file if they aren't found. In the case that the variables are set using environment variables (i.e. CI production or staging) the variables are not saved in a local file to improve the security.
More info: https://issues.gpii.net/browse/GPII-2833

GPII-2833 - Add persistence to auto generated variables

---

README.md

More details in ticket: https://issues.gpii.net/browse/GPII-2827
One thing that's neat is we update the kops cluster configuration every time, even for existing clusters.
For now, I stopped short of running `kops rolling-update cluster` every time, which would make configuration changes take effect immediately and automatically. The operation is available manually via the new target `rake kops_rolling_update`.

GPII-2827: spike: CIS Kubernetes hardening standard

---

README.md
modules/deploy/Rakefile
modules/deploy/secrets/alertmanager.yaml.erb

Alertmanager email is now Amazon SES.

GPII-2886 Add secrets[:alertmanager_email_auth_username].

---

.gitlab-ci.yml
aws/README.md
gcp/README.md
gcp/Rakefile
gcp/rakefiles/tests/Gemfile
gcp/rakefiles/tests/Gemfile.lock
gcp/rakefiles/tests/Rakefile
gcp/rakefiles/tests/spec/vars_spec.rb
gcp/rakefiles/vars.rb

This isn't quite done, but nothing uses this code yet so feel free to merge if it will help you start integrating.
I used TDD to write the new vars.rb. I looked at using minitest, which Alfredo introduced to test merge_yaml.rb, but I needed mocks to work with ENV. I decided to switch to rspec since AFAIK it is the most popular way to test in ruby and it gives us more options for testing later (there are rspec matchers for all kinds of things).
The next few problems on my todo list:
1. The system doesn't work when I `rake dev:deploy`, then `rake dev:destroy`, then `rake dev:deploy` again:
```
Error enabling service: Error enabling service ["containerregistry.googleapis.com"] for project "xk-tyler9": Error waiting for api to enable:
googleapi: Error 403: The caller does not have permission, …
```

GPII-2990: rake glue for exekube-based project

---

aws/modules/deploy/Rakefile
aws/rakefiles/deploy.rake

This manifested as a bug where cert-manager isn't deployed before flowmanager/preferences try to use the Certificate TPR, leading to this confusing error:
```
Error: apiVersion "certmanager.k8s.io/v1alpha1" in gpii-flowmanager/templates/certificate.yaml is not available
```

Sort helm charts to ensure correct ordering.

---

gcp/rakefiles/entrypoint.rake
gcp/rakefiles/secrets.rb
gcp/rakefiles/sh_filter.rb
gcp/rakefiles/utils.rb
gcp/rakefiles/vars.rb

This is more like a proof-of-concept, but it does the job even in its current state:
```module.gpii-flowmanager.null_resource.helm_template: Creating...
triggers.%:      "" => "2"
triggers.chart:  "" => ""
triggers.values: "" => "replicaCount: 2\n\nimage:\n  repository: gpii/universal\n  checksum: sha256:d0b69df1e900912eab6db7185c5d998c25729f0bffeec0996ec433a750b52b64\n\nissuerRef:\n  name: letsencrypt-staging\n  kind: ClusterIssuer\n\ndnsNames:\n- flowmanager.natarajaya.dev.gcp.gpii.net\n\ningress:\n  disable_ssl_redirect: true\n\nmatchmaker_url: \"http://flowmanager.natarajaya.dev.gcp.gpii.net\"\n\ndatasource_hostname: \"http://<sensitive>:<sensitive>@couchdb-svc-couchdb.gpii.svc.cluster.local\"\n"```

Obfuscate sensitive data in deploy task output

---

gcp/rakefiles/entrypoint.rake

It is way more convenient for development/debugging purposes, than waiting until `destroy_module` task finishes (can be minutes in case of couchdb, for example) only to call `deploy_module`.

Adding :redeploy_module utility task

---

aws/README.md

It turns out gem won't downgrade gems, so bump our version to the
default provided by the latest rvm 2.4.3.

GPII-3155: bump bundler version.

---

aws/rakefiles/vars.rb

This is kind of crude, and duplicates information in both aws/README.md
and ansible-gpii-ci-worker.
However, there are often painful consequences for accidentally using the
wrong version of some key tools, e.g. a new version of terraform
upgrading remote state and making it incompatible with earlier versions,
or a new version of kops triggering an unexpected rolling-update.

GPII-3103: Check versions of key tools.

---

aws/rakefiles/vars.rb

This is a follow up to #49. In fact, the first commit is exactly the change from #49 (though it's probably easier to read both diffs together).
I'm going to merge this so I can verify in CI, but please comment if you see a better solution.

GPII-3103: Make check_versions work during/after 'rake clobber'.

---

aws/rakefiles/deploy.rake

The previous /settings endpoint is no longer testable with GPII-1990 work in the universal branch.

GPII-1990: Test CBFM using /access_token endpoint

---

gcp/live/dev/k8s/kube-system/k8s-snapshots/terraform.tfvars

GCP master is failing because of this.

Adding missing dependency on helm-initializer to k8s-snapshots Terragrunt module

---

gcp/docker-compose.yaml
gcp/modules/couchdb/main.tf
gcp/rakefiles/tests/spec/vars_spec.rb
gcp/rakefiles/vars.rb

This is the only way to force Terraform to apply resource on every run that I am aware of. It will give us the ability to workaround probable narrow points, similar to the situation, where we need to patch CouchDB PVs manually, described in the comments to #58.

Introducing TF_VAR_nonce, applying CouchDB PVs patch on every run

---

aws/dev/Rakefile
aws/prd/Rakefile
aws/rakefiles/deploy.rake
aws/stg/Rakefile

@mrtyler The reason behind that `Unauthorized` error is that `:undeploy` deletes Tiller's SA and CRB, while keeping deployment intact. On the next `rake` run, it recreates missing system resources, but it does not help.
I can think of couple solutions:
1. Delete Tiller deployment at the end of `:undeploy`, let `helm init --upgrade` recreate it on next `rake` run.
2. Do not delete system components during `:undeploy`.
Considering typical dev workflow, **2** makes more sense to me, so I implemented it here. There is probably no need to undeploy stuff that we have in `modules/deploy/system` (namespaces, SAs, CRBs, etc.) at all, since it is currently safe to leave all of that in the cluster. However, I decided to not change how `:destroy` task currently works, which should give us more …

GPII-3216: Rake :undeploy should not delete system components by default

---

aws/modules/deploy/charts/config.yml
aws/rakefiles/deploy.rake

This should prevent annoying 60 seconds of retries during `gpii-dataloader` chart upgrade.

GPII-3197: Adding allow_upgrade chart config flag

---

USER-TRAINING.md
aws/README.md
aws/modules/k8s/Rakefile
aws/rakefiles/deploy.rake

Scenarios I tested:
* Create dev cluster from scratch with k8s 1.8.15
* Create dev cluster from scratch with k8s 1.8.7, upgrade to 1.8.15
* Create dev cluster from scratch with t2.medium Nodes, upgrade to c4.xlarge Nodes
Everything went smoothly (except for that thing Prometheus started doing where it comes up with an empty /rules mount :/).
Note that upgrading existing clusters like stg and prd will require some manual steps. I added documentation about how this works after I tried to do it and discovered that I had forgotten how it works :).
Once we merge this, push the upgrade through prd, and prove that it all works, I might bump us back down to t2.medium until we're ready for traffic -- just so we're not paying for quite so many c4.xlarge hours. Anyone think this is not worth the …

Gpii 3200 bumps

---

aws/modules/k8s/Rakefile

c5.* (and m5.*) Instances changed where Volumes get mounted on the host,
leading to widespread failure in PV[C]s getting re-mounted after a
kops rolling-update.
https://github.com/kubernetes/kubernetes/issues/49926

GPII-3200: Back to c4.xlarge.

---

gcp/modules/gcp-secret-mgmt/main.tf

Accidentally left this behind after couple experiments with `gcp-secret-mgmt` exekube's module.

Remove storage class variable in gcp-secret-mgmt

---

aws/README.md
aws/rakefiles/deploy.rake
aws/rakefiles/kops.rake

Based on watching Sergey go through the manual upgrade process.
Here's the updated output of `rake display_cluster_info`:
```
******************************************
Congratulations! Your GPII Cloud is ready!
******************************************
AWS Dashboard Resource Group:
https://resources.console.aws.amazon.com/r/group#sharedgroup=%7B%22name%22%3A%22stg.gpii.net%22%2C%22regions%22%3A%22all%22%2C%22resourceTypes%22%3A%22all%22%2C%22tagFilters%22%3A%5B%7B%22key%22%3A%22KubernetesCluster%22%2C%22values%22%3A%5B%22stg.gpii.net%22%5D%7D%5D%7D
Metrics, Graphs, and Alerts
First, port-forward some or all of the applications (probably in a separate window):
kubectl --namespace monitoring port-forward prometheus-k8s-0 9090 & \
kubectl --namespace monitoring port-forward …
```

GPII-3200: Improve docs.

---

aws/rakefiles/kops.rake

This is in response to an intermittent failure in `:kops_rolling_update`, "Unable to reach the kubernetes API." E.g. in https://gitlab.com/gpii-ops/gpii-infra/-/jobs/84470317.
I didn't test this very much, but I think it's safe. `kops rolling-update` seems to be reasonably idempotent even in the face of several failure modes.

wait_for kops rolling-update

---

aws/README.md

Rendered markdown:
https://github.com/mrtyler/gpii-infra/tree/GPII-3199-contact/aws#production-is-broken-theres-been-a-security-breach-or-there-is-some-other-operational-emergency
This is a start to a process that will certainly evolve. For now, the goal is to provide *something* in case we have an operational emergency during the August demos or similar.
This may warrant some real-time discussion. I'll raise it in the next standup.

GPII-3199: what to do if production is broken

---

.gitlab-ci.yml

Otherwise you get 'variables config should be a hash of key value pairs'
This is a follow-up fix to #73. I tested it the hard way, but this version works: https://gitlab.com/gpii-ops/gpii-infra/pipelines/26609776

Apparently this value needs quoting.

---

gcp/docker-compose.yaml
gcp/modules/cert-manager/main.tf
gcp/modules/couchdb/main.tf
gcp/modules/gpii-dataloader/main.tf
gcp/modules/gpii-flowmanager/main.tf
gcp/modules/gpii-preferences/main.tf
gcp/modules/k8s-snapshots/main.tf
gcp/modules/nginx-ingress/main.tf
gcp/rakefiles/entrypoint.rake
gcp/rakefiles/secrets.rb

* Fixed gpii modules to use `helm-release` instead of `helm-template-release` for consistency
* Moved `charts_dir` to docker-compose config
* We don't need `values_dir` to be mounted from host machine, use temp dir instead and render templates on every run

GCP: Various fixes

---

aws/README.md
aws/rakefiles/deploy.rake

This solves [GPII-3196](https://issues.gpii.net/browse/GPII-3196).
- Add check for certificate K8s resource being created
- Add a note to README about curl dependency on older macOS to resolve the SNI issue mentioned in the ticket. This is not required on High Sierra and newer, since macOS switched its native curl version to one based on LibreSSL (as opposed to one based on Secure Transport previously)
Tested cluster creation & destroy.
(this could also be solved by containerising everything, but this was discussed in https://github.com/gpii-ops/gpii-infra/pull/82)

GPII-3196 Improve certificates check

---

aws/modules/deploy/charts/values/gpii-flowmanager.erb
aws/modules/deploy/charts/values/gpii-preferences.erb
aws/rakefiles/deploy.rake
common/charts/gpii-flowmanager/templates/deployment.yaml
common/charts/gpii-flowmanager/values.yaml
common/charts/gpii-preferences/templates/deployment.yaml
common/charts/gpii-preferences/values.yaml

--recreate-pods on a helm upgrade restarts all services and prevents us from keeping the services available during upgrades. This PR removes this particular flag as well as promotes a expand-then-contract model for the rolling updates during deployments.

GPII-3215: Don't use --recreate-pods

---

gcp/rakefiles/ci.rake
gcp/rakefiles/xk.rake

Fixes a bug where Serviceaccount Keys were being created too often. See also GPII-3299.

GPII-2996: Don't create so many Keys.

---

.gitlab-ci.yml

The former deletes the terragrunt volume, which the latter re-creates. The new order avoids this double dribble.

GPII-2996: Re-order destroy_tfstate and destroy_secrets.

---

gcp/rakefiles/entrypoint.rake

Due to unknown reasons `gsutil rm` hangs if multi-threaded mode enabled and there is nothing to remove:
```
bash-4.4# gsutil -m rm -r gs://gpii-gcp-dev-natarajaya-tfstate/dev/k8s
CommandException: 1 files/objects could not be removed.
^CCaught CTRL-C (signal 2) - exiting
```

Disable multi-threaded mode for gsutil in :destroy_tfstate

---

aws/modules/deploy/charts/values/gpii-flowmanager.erb
common/charts/gpii-flowmanager/README.md
common/charts/gpii-flowmanager/templates/deployment.yaml
common/charts/gpii-flowmanager/values.yaml
gcp/modules/gpii-flowmanager/values.yaml

Removes unused GPII_FLOWMANAGER_MATCHMAKER_URL env variable from Flowmanager chart and corresponding bits

GPII-3214 - Remove unused GPII_FLOWMANAGER_MATCHMAKER_URL variable

---

gcp/rakefiles/entrypoint.rake
gcp/rakefiles/secrets.rb
gcp/rakefiles/xk.rake

This contains a fix for illegal base64 data in `tfstate_encryption_key` issue.
While working on that I had to fix the way we set secrets from ENV vars: since secrets are being handled inside of the exekube container, and only `TF_VAR_` vars are being passed, it is impossible to set secrets using `ENV[secret_name.upcase]` anymore.
I also found that infra is being applied twice, because of prerequisite of `:deploy` task and direct invocation from `:xk` task, fixed as well.

[GPII-3329]: Various fixes

---

gcp/live/dev/Gemfile
gcp/live/dev/Gemfile.lock
gcp/live/dev/Rakefile
gcp/live/dev/spec/network_spec.rb

This PR contains an early draft of code that allows us to test-drive development of network security policies on GCP. There are a large number of improvements that can/will be made. Notably:
1. Potential inclusion of a more domain-specific frameworks like `serverspec`, `inspec`, `goss`, or `gauntlt`
1. Execution of code within a standard container (perhaps the same container as the exekube container)
1. Documentation
1. Improved rspec matchers to improve readability (may be obviated by (1)) 
1. Move of securityTest related task definitions to its own Rake file
Currently, the way to execute this is to execute `rake securityTest` in `gcp/live/dev`. The output looks like the following:
```
$ rake securityTest
/usr/local/rvm/rubies/ruby-2.5.1/bin/ruby …
```

GPII-3248: Draft up initial ideas on testing security of GCP-based clusters

---

gcp/rakefiles/test.rake

This was increased temporarily to account for the extra time that the first query to the preferences server was taking. Now that the indices are warmed up, the first query should not take as long.

GPII-3250: Change locust_desired_max_response_time back to its defaults

---

gcp/rakefiles/xk.rake

@stepanstipl reported (and @natarajaya confirmed) a bug in `:sh`'s dependencies. This fixes it for me, verified with `rake clobber && rake sh`.

Update dependency on serviceaccount auth.

---

common/live/prd/infra/dev/sergio/terraform.tfvars
common/live/prd/infra/dev/stepan/terraform.tfvars

Before merge this PR. As @seg10 has an already created project, the existing resources must be imported first, in order to avoid conflicts at the project creation.
```
cd common/live/prd
RAKE_REALLY_RUN_IN_PRD=yes rake plain_shell
cd live/prd/infra/dev/sergio/
terragrunt import google_project.project gpii-gcp-dev-seg10
terragrunt import google_project_services.project gpii-gcp-dev-seg10
terragrunt import google_storage_bucket.project-tfstate gpii-gcp-dev-seg10-tfstate
terragrunt import google_service_account.project projects/gpii-gcp-dev-seg10/serviceAccounts/projectowner@gpii-gcp-dev-seg10.iam.gserviceaccount.com
```
As the importing of a DNS don't work, the delete of the zone and the NS registry in the dev.gcp.gpii.net are also needed.
```
#The following didn't work in other cases …
```

Add Sergio and Stepan dev clusters

---

shared/rakefiles/xk.rake

https://issues.gpii.net/browse/GPII-3351
"The actual implementation of the detection if a DNS zone already exists relies on the fact that there is an output in the tf state. That could not be the case if the project is recently created. The output of this DNS resource is only saved once a new cluster is created inside the project."
This PR also solves this comment of the #60 : https://github.com/gpii-ops/gpii-infra/pull/60#pullrequestreview-154394605

GPII-3351 - Change the way that the DNS zone is detected in GCP

---

.gitlab-ci.yml

This will allow for branches to be created in `gpii-ops/gpii-infra` without triggering the pipeline.

Ensure that gitlab pipeline runs only on master

---

common/modules/gcp-project/main.tf

This change avoid the "fighting" between exekube and the common gcp-project Terraform module where each one sets a different description of the DNS zone.

GPII-3361 - Remove DNS description and leave default as it is in exekube

---

.gitlab-ci.yml
TESTING.md

This PR details out the path forward on how to bring up the frontend app locally and how to tie it into a custom cluster.

GPII-3248: Add testing notes for manually testing the front-end app with the backend apps on the cloud

---

common/modules/gcp-project/main.tf

Some APIs are needed to enable the logging feature

GPII-3377- Enable logging APIs

---

shared/rakefiles/test.rake

For now, we'll increase the max response time while we figure out why the GCP cluster is underperforming after the latest batch of integrations. There will be a follow-up ticket to either restore this
setting or set it to a more appropriate level.

GPII-3375: Increase max response time while troubleshooting

---

aws/modules/deploy/53-couchdb-statefulset.erb
common/charts/couchdb/Chart.yaml
common/charts/couchdb/README.md
common/charts/couchdb/values.yaml

The https://github.com/gpii-ops/couchdb-docker/pull/2 is also needed. Although the CouchDB container is already built and tested.
I updated the chart from [the incubator](https://github.com/helm/charts/tree/master/incubator/couchdb) and added the code needed to provide the "affinity" feature from Sergey's PR: https://github.com/helm/charts/pull/7224
Since we don't have the commit history of upstream, I checked out the repository and see the differences with upstream, applying them in our branch.

GPII-3387 Upgrade CouchDB 2.2.0 due security vulnerabilities

---

README.md

Given the increasing number of markdown files, we should help to ensure that someone can navigate to them from the top level README.md file.
Note that this PR addresses a single comment from the previous PR for GPII-3248: https://github.com/gpii-ops/gpii-infra/pull/111#discussion_r216551489.

GPII-3248: Add links from README.md to additional documentation

---

.gitignore
aws/modules/deploy/charts/config.yml
aws/rakefiles/vars.rb

This fixes:
```
Error: could not find a ready tiller pod
helm install --name nginx-ingress --namespace gpii -f /tmp/rake-tmp/dev-gitlab-runner-modules/deploy/charts/values/nginx-ingress.yaml ../../common/charts/nginx-ingress
```

Fix the location of the charts

---

gcp/modules/gke-cluster/main.tf

Merge after https://github.com/gpii-ops/exekube/pull/15

[GPII-3395]: Increase update timeout for GCP cluster

---

gcp/live/terraform.tfvars
gcp/modules/nginx-ingress/main.tf
shared/rakefiles/secrets.rb
shared/rakefiles/xk.rake

Small update on how we got here:
* CI [sometimes fail](https://gitlab.com/gpii-ops/gpii-infra/-/jobs/98913039) with `Error configuring the backend "gcs": Error decoding encryption key: illegal base64 data at input byte 0`.
* Recovered TF state encryption keys looked valid.
* We tried to change base64 encoding standard  that is used from RFC 2045 to RFC 4648, the failure rate decreased (may be coincidence), but issue was still there.
* Pulled up Terraform GCS backend code and tried to decrypt keys under question using [exact Go code](https://github.com/hashicorp/terraform/blob/master/backend/remote-state/gcs/backend.go#L184-L188) from GCS backend – all keys appeared to be valid during tests.
* Discovered that GCS backend also provides a way to set encryption key [using …

[GPII-3329]: Workaround for Terraform GCS backend encryption issue

---

.gitlab-ci.yml
shared/rakefiles/entrypoint.rake

Extra protection for prd. See https://github.com/gpii-ops/exekube/pull/16.
```
[tyler@toaster:~/rtf/gpii-infra/gcp/live/prd]$ rake destroy_module"[k8s/stackdriver/export]"
ERROR: Tried to run in env 'prd' but RAKE_REALLY_RUN_IN_PRD is not set
rake aborted!
[tyler@toaster:~/rtf/gpii-infra/gcp/live/prd]$ RAKE_REALLY_RUN_IN_PRD=1 rake destroy_module"[k8s/stackdriver/export]"
ERROR: Tried to destroy something in env 'prd' but RAKE_REALLY_DESTROY_IN_PRD is not set
rake aborted!
ArgumentError: Tried to destroy something in env 'prd' but RAKE_REALLY_DESTROY_IN_PRD is not set
[tyler@toaster:~/rtf/gpii-infra/gcp/live/prd]$ RAKE_REALLY_RUN_IN_PRD=1 RAKE_REALLY_DESTROY_IN_PRD=1 rake destroy_module"[k8s/stackdriver/export]"
docker-compose run --rm xk rake xk['down …
```

Add :check_destroy_allowed.

---

gcp/modules/couchdb/values.yaml
gcp/modules/gpii-flowmanager/values.yaml
gcp/modules/gpii-preferences/values.yaml
gcp/modules/nginx-ingress/values.yaml

@stepanstipl I had to return back to my original requests settings for CPU. Looks like the reason of recent build failures is too intense CPU throttling. And since we have only 6 CPUs in the cluster, out of which [almost 5 CPUs are already requested](https://www.dropbox.com/s/abderjo09nl61xc/Screenshot%202018-09-28%2021.46.56.png?dl=0), I was unable to divide remaining 1 CPU between all GPII components without causing issues with scheduling. However, when I set higher CPU limits, system performance significantly improves.
I suggest we keep this as it is for now and revisit in future (maybe when we introduce more powerful instances for stg/prd?)

Tune CPU requests for GPII components

---

common/live/stg/infra/dev/doe/terraform.tfvars
common/live/stg/infra/dev/zone/terraform.tfvars
common/live/stg/infra/prd/zone/terraform.tfvars
common/live/stg/infra/stg/zone/terraform.tfvars

The PR https://github.com/gpii-ops/gpii-infra/pull/155 has wrong groups definition for the testing organization, causing failures in the pipeline https://gitlab.com/gpii-ops/gpii-infra/-/jobs/103826443

Change a valid group for the testing organization

---

gcp/live/dev/k8s/cluster/terraform.tfvars
gcp/live/dev/k8s/gpii/couchdb/terraform.tfvars
gcp/live/dev/k8s/gpii/flowmanager/terraform.tfvars
gcp/live/dev/k8s/gpii/preferences/terraform.tfvars
gcp/live/prd/k8s/cluster/terraform.tfvars
gcp/live/prd/k8s/gpii/couchdb/terraform.tfvars
gcp/live/prd/k8s/gpii/flowmanager/terraform.tfvars
gcp/live/prd/k8s/gpii/preferences/terraform.tfvars
gcp/live/stg/k8s/cluster/terraform.tfvars
gcp/live/stg/k8s/gpii/couchdb/terraform.tfvars
gcp/live/stg/k8s/gpii/flowmanager/terraform.tfvars
gcp/live/stg/k8s/gpii/preferences/terraform.tfvars
gcp/modules/couchdb/main.tf
gcp/modules/couchdb/values.yaml
gcp/modules/gke-cluster/main.tf
gcp/modules/gpii-flowmanager/main.tf
gcp/modules/gpii-flowmanager/values.yaml
gcp/modules/gpii-preferences/main.tf
gcp/modules/gpii-preferences/values.yaml
gcp/modules/nginx-ingress/values.yaml

This is the long-term solution I promised.
For dev clusters I had to keep requests lowered in order to stay on cheaper `n1-standard-2` nodes.
For staging / prod clusters:
* To have "more predictable" scheduling with requests = limits
* To also have more replicas of preferences, flowmanager and couchdb (similarly to AWS setup)
* And finally, to have enough room for rolling updates with `maxUnavailable: 0`
I suggest to use `n1-highcpu-4` instances. They are a bit cheaper than `n1-standard-4` and have significantly less RAM (4GB vs 15GB), but since we are very far away from hitting RAM limit, it seems like the most optimal choice in our situation.
Changing node type will most likely cause Terraform to attempt to recreate the cluster. I am not sure if there is a way around this issue for …

[GPII-3418]: Tune resource requests one more time

---

gcp/live/prd/k8s/gpii/flowmanager/terraform.tfvars
gcp/live/prd/k8s/gpii/preferences/terraform.tfvars
gcp/live/stg/k8s/gpii/flowmanager/terraform.tfvars
gcp/live/stg/k8s/gpii/preferences/terraform.tfvars

Even with `n1-highcpu-4` nodes, I am still getting insufficient cpu warnings and unschedulable pods.

Decrease preferences, flowmanager replica count for stg, prd

---

gcp/docker-compose.yaml
shared/rakefiles/entrypoint.rake

This PR fixes issues described in [GPII-3428](https://issues.gpii.net/browse/GPII-3428). There's a couple of different cases I was able to reproduce, all related to Terragrunt's caching of modules and providers.
The behavior without the volume is more consistent with what happens on CI, where we delete the volumes between runs.
The particular issue described can be reproduced by:
- Run `rake` in `gcp/dev/`
- Change version of one of the TF providers (I've changed `helm` to 0.5 for testing) and build `gpii/exekube:0.4.0-google` image
- Run `rake` again and you should get the error.
There seems to be slight performance hit on average by not using the volume, as `init` has to be run every time:
| # | with volume | without volume |
| --- | --- | --- |
| 1st | 2:08s | 1:57s |
| 2nd | 1:53s | …

GPII-3428 Remove terragrunt volume

---

shared/rakefiles/entrypoint.rake

This workaround should not be needed anymore. Docker for Mac stable  now has 18.06.1 and fix for this should be present since `18.06.0-ce-mac70 (26399)` (https://github.com/docker/for-mac/issues/2076)

Remove hwclock hack for mac

---

.gitlab-ci.yml

We are rotating tfstate key for prefix `k8s`, but leaving `locust` behind.

Destroy TF state for locust in stg and prd

---

gcp/modules/gke-cluster/main.tf

`* google_container_cluster.cluster: googleapi: Error 400: Master version "1.10.7-gke.2" is unsupported., badRequest`
I haven't tested upgrading an existing cluster; I think that was a pain last time? Anyway I hit the above error so I thought I'd start the ball rolling on the (mandatory) upgrade.

Bump kubernetes_version to 1.10.7-gke.6.

---

gcp/modules/gpii-dataloader/main.tf

This is an ugly hack to stop TF/Helm data loader errors that freezes data loader version.
It should be removed in scope of https://github.com/gpii-ops/gpii-infra/pull/163, once the "new" dataloader is ready to be used.
After potentially failing once (if the dataloader is at older version), no more errors should appear, as TF will not try to update it even if `versions.yaml` change.

Hack to stop dataloader related errors

---

gcp/modules/couchdb/main.tf
shared/charts/couchdb/templates/statefulset.yaml

This fixes CouchDB updates by removing `Version` part from StatefulSet label, as Kubernetes don't allow updates to any other fields but 'replicas', 'template', and 'updateStrategy' (https://issues.gpii.net/browse/GPII-3421).
Also adds `force_update` to the CouchDB and this will cause StatefulSet recreation, but without it we wouldn't be able to update, as the chart is already deployed with the `Version` in the label.
While this causes CouchDB downtime, the underlying volumes and therefore data are preserved. In future we should be carefull about updates that modify anything but the fields mentioned above.
From the tests on my cluster:
PVC and associated PVs before the update:
```
$ kubectl get pvc -n gpii
NAME                                 STATUS    VOLUME …
```

GPII-3421 - Allow couchdb updates

---

gcp/modules/gcp-secret-mgmt/config.yaml
shared/rakefiles/secrets.rb

As discovered by Alfredo, Terraform freaks out in case order of the encryption keys changes.

[GPII-3456] Add encryption keys config to keep the order

---

common/modules/gcp-project/main.tf
gcp/live/prd/k8s/cluster/terraform.tfvars
gcp/live/stg/k8s/cluster/terraform.tfvars
gcp/modules/gke-cluster/main.tf
gcp/modules/gpii-flowmanager/values.yaml
gcp/modules/gpii-preferences/values.yaml
shared/charts/gpii-flowmanager/README.md
shared/charts/gpii-flowmanager/templates/deployment.yaml
shared/charts/gpii-flowmanager/values.yaml
shared/charts/gpii-preferences/README.md
shared/charts/gpii-preferences/templates/deployment.yaml
shared/charts/gpii-preferences/values.yaml

Does nothing until https://github.com/GPII/universal/pull/703 is merged.
Tested in my dev environment with GPII_ENABLE_STACKDRIVER_TRACE both enabled and disabled.
Also (unrelatedly) adds a Terragrunt module dependency I missed earlier.

GPII-3394: Enable Stackdriver Trace

---

aws/README.md
aws/modules/deploy/charts/config.yml
aws/rakefiles/deploy.rake

This brings new dataloader to AWS infra as well. I've verified state of AWS database and it's consistent with GCP (at least the entries relevant for this change). Steps to deploy are same as the ones for gcp part (see https://github.com/gpii-ops/gpii-infra/pull/163 for details).
This PR also removes docs about dataloader, as there's nothing special about the dataloader anymore, it now lives as part of universal and not an individual project. Dataloader itself is documented at https://github.com/GPII/universal/blob/master/documentation/DataLoader.md and does not require any special treatment from the infra point of view.

GPII-3391: New dataloader for aws

---

gcp/live/prd/k8s/cluster/terraform.tfvars
gcp/live/stg/k8s/cluster/terraform.tfvars
gcp/modules/gke-cluster/main.tf

Requires https://github.com/gpii-ops/exekube/pull/23.
As punishment for my hubris in saying this feature would be simple to add, Terraform does not support variable interpolation in `lifecycle{}` blocks :(. https://github.com/hashicorp/terraform/issues/3116
Fortunately, @zero-below posted a workaround (thanks, friend!). The workaround is a little weird but with it I was able to protect a cluster, un-protect it, re-create it, and re-protect it.

GPII-3492: Allow us to (optionally) prevent destruction of the cluster. (gpii-infra)

---

common/modules/gcp-project/main.tf
shared/rakefiles/entrypoint_common.rake
shared/rakefiles/xk_infra.rake

The common SA has owner permissions at organization level and also at the project level.
At the organization level it needs the `owner` permissions in order to grant itself the permissions of modifying IAMs. Once the common SA has the right permissions it doesn't need to reset them again, so we can delegate this task to an operator and remove the owner permission to the SA at organization level. If the common SA doesn't have proper permissions the CI pipeline will fail at the `apply_common_infra` task.
At the project level it also has the `owner` role. This PR set the roles collected based on the audit logs queries and some test deployments. This PR also assign lower level permissions to the user SA.
The plan to proceed with this PR, as it affects to the entire infrastructure, is to merge …

GPII-3354 Restrict permissions to the common SA

---

common/modules/gcp-project/main.tf

GPII-3354 Add Service Account Key Admin to allow the destroy of unused keys

---

gcp/modules/locust/swarm.tf
shared/rakefiles/test.rake

This prevents `CustomerEncryptionKeyIsIncorrect` errors in situations such as described in the ticket.

[GPII-3498]: Destroy Locust TF state before test

---

gcp/modules/couchdb/main.tf

This should prevent us from having split-brain scenarios caused by untimely executed `finish_cluster` action.

[GPII-3494]: Check for cluster membership instead of pod status in finish_cluster

---

common/modules/gcp-project/main.tf
shared/rakefiles/xk_infra.rake

Patch for #190 
@stepanstipl and I discovered that the common SA of the testing organization had owner permissions inherited by an admin group, making all my old tests not valid. This PR sets the proper permissions of the common SA at the organization level an also at the project level.

GPII-3354 - Set proper common permissions at organization level

---

gcp/modules/gke-cluster/main.tf

This is a part of the deployment plan for https://github.com/gpii-ops/gpii-infra/pull/204.

Disable destroy prevention for gke-cluster

---

gcp/modules/gke-cluster/main.tf

Reverts gpii-ops/gpii-infra#214 as part of the deployment plan for #204.

Revert "Disable destroy prevention for gke-cluster"

---

shared/charts/couchdb/Chart.yaml
shared/charts/couchdb/templates/statefulset.yaml

These are additional changes re. allowing CouchDB updates to align with upstream Chart and changes requested by the `helm/charts` maintainers on the PR against upstream.
I intend to merge this only after the upstream PR is merged - https://github.com/helm/charts/pull/8527

GGPII-3421 - Align with upstream chart changes

---

gcp/modules/couchdb/main.tf
shared/charts/couchdb/Chart.yaml
shared/charts/couchdb/README.md
shared/charts/couchdb/templates/statefulset.yaml
shared/charts/couchdb/values.yaml

This brings in changes from upstream CouchDB chart:
- last bits related to my work on updatability - https://github.com/helm/charts/pull/8527  PR got finally merged
- 2 other cosmetic changes where upstram was different
It also disables `force_update` on the CouchDB chart - it should not be needed anymore as the chart can now be updated without errors.

Sync CouchDb chart from upstream

---

gcp/modules/couchdb/main.tf
gcp/modules/gcp-stackdriver-lbm/resources/log_based_metrics/compute_firewalls.json
gcp/modules/gcp-stackdriver-lbm/resources/log_based_metrics/disks_createsnapshot.json
gcp/modules/gcp-stackdriver-lbm/resources/log_based_metrics/pods_exec_create.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/firewalls_activity.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/k8s_snapshots_couchdb.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/k8s_snapshots_errors.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/pod_exec.json

Changes included in this PR:
- New log-based metric and alert policy to monitor audit events for `kubectl exec` (which is the only way to get a shell into running container, because we do not allow ssh access to worker nodes).
- Changes to CouchDB module to perform cluster finalization using port forwarding instead of `kubectl exec` .
- Log-based metric and alert policy to monitor firewall patch / insert events, though I am not sure if this is necessary (mostly because now, if person has edit access to firewall rules, they can also edit alert policies).
- New log-based metric to count `compute.disks.createSnapshot` audit events, added condition on that metric to CouchDB snapshots check policy, to improve its reliability (track actual snapshot creation events and not just records from …

[GPII-2863]: Update log-based metrics, alert policies

---

gcp/README.md
gcp/modules/gcp-stackdriver-monitoring/resources/notification_channels/alerts_slack.js
shared/rakefiles/stackdriver.rb

I authorized Stackdriver to send notifications to RTF Slack *#alerts* channel for `gpii-gcp-stg` and `gpii-gcp-prd` projects (see instructions in [updated README](https://github.com/natarajaya/gpii-infra/blob/5fa2511d3e639e970a354101d2c8f8cbda4cbf24/gcp/README.md#to-receive-notifications-in-slack)).
This adds Slack notification channel config and changes to Stackdriver Ruby client to work properly with Slack notification channels.

[GPII-3566]: Enable Stackdriver Slack notifications for stg, prd

---

gcp/modules/gcp-stackdriver-monitoring/resources/notification_channels/alerts_prd_slack.js
gcp/modules/gcp-stackdriver-monitoring/resources/notification_channels/alerts_stg_slack.js

There is no need to set which channel to use by environment – since they are immutable, the one that exists in Stackdriver workspace will be picked up by alert policies and other ignored.
Things to to after this is deployed:

Use alerts-stg and alerts-prd Slack channels

---

gcp/modules/gke-cluster/main.tf
shared/rakefiles/xk.rake

This PR upgrades GKE version to `1.11` and changes cluster type to `regional`. Depends on https://github.com/gpii-ops/exekube/pull/27.
**This will force cluster re-creation** as changing from zonal to regional cluster type requires it.
There are issues with cluster upgrade to `1.11` (see https://issues.gpii.net/browse/GPII-3568 for details), but these are effectively resolved by re-creating the cluster, therefore it makes sense to do these two changes together. *(TL;DR if you upgrade manually and your cluster is broken after  the upgrade, you'll see crashing `calico-node-*` pods and this can be resolved by deleting `globalbgpconfig` resources - `kubectl delete globalbgpconfig {asnumber,nodemeshenabled,loglevel} -n kube-system`).*
Due to way this was implemented in exekube (to preserve …

Upgrade GKE to 1.11 and regional clusters

---

gcp/modules/couchdb-prometheus-exporter/values.yaml
gcp/modules/gpii-dataloader/values.yaml
gcp/modules/gpii-flowmanager/values.yaml
gcp/modules/gpii-preferences/values.yaml
shared/charts/couchdb-prometheus-exporter/README.md
shared/charts/couchdb-prometheus-exporter/templates/deployment.yaml
shared/charts/couchdb-prometheus-exporter/values.yaml
shared/charts/fluentd/templates/configmap.yaml
shared/charts/gpii-dataloader/README.md
shared/charts/gpii-dataloader/templates/job.yaml
shared/charts/gpii-dataloader/values.yaml
shared/charts/gpii-flowmanager/README.md
shared/charts/gpii-flowmanager/templates/deployment.yaml
shared/charts/gpii-flowmanager/templates/ingress.yaml
shared/charts/gpii-flowmanager/templates/service.yaml
shared/charts/gpii-flowmanager/values.yaml
shared/charts/gpii-preferences/README.md
shared/charts/gpii-preferences/templates/deployment.yaml
shared/charts/gpii-preferences/templates/ingress.yaml
shared/charts/gpii-preferences/templates/service.yaml
shared/charts/gpii-preferences/values.yaml

This removes an unused variable I discovered while working on GPII-3394 and a naming inconsistency Stepan noticed while reviewing my work on GPII-3394.
I used this atrocious one-liner plus manual tweaking to revert some false positives (also, BSD sed's '-i' flag was giving me trouble):
```
unset expr ; for var in $(git grep '`\S\+_' shared/ | grep -v '/_stats' | grep -v rotate_secrets | awk -F'`' '{print $2}') ; do camel_var=$(echo $var | ruby -pne 'gsub(/_(\w)/){$1.upcase}') ; expr="${expr} -e s/$var/$camel_var/g" ; done ; for file in $(find shared/ -type f) $(find . -name values.yaml) ; do sed $expr -i FFFUUU $file ; done ; find . -name '*FFFUUU' | xargs rm
```
I deployed my dev environment from scratch and it came up so hopefully that means I renamed everything correctly.

GPII-3394: Chart variable cleanups

---

gcp/README.md

Edited the notes from our standup discussion, prompted by [this PR discussion](https://github.com/gpii-ops/gpii-infra/pull/230#pullrequestreview-183561343).
[Rendered markdown](https://github.com/mrtyler/gpii-infra/blob/gpii-3394-resources/gcp/README.md#kubernetes-resource-requests-and-limits).

Add README guidance about Kubernetes resource requests and limits.

---

gcp/modules/couchdb/main.tf

Fixes `rake destroy` getting stuck on destroying PVCs. Allso adds `--grace-period` which should force `kubectl` not to get stuck forever even if it can't delete PVCs nicely.

GPII-3601: Fix destroying pvcs ordering

---

gcp/live/dev/k8s/stackdriver/monitoring/terraform.tfvars
gcp/live/prd/k8s/stackdriver/monitoring/terraform.tfvars
gcp/live/stg/k8s/stackdriver/monitoring/terraform.tfvars
gcp/modules/gcp-stackdriver-lbm/main.tf
gcp/modules/gcp-stackdriver-monitoring/main.tf
gcp/modules/gcp-stackdriver-monitoring/resources/notification_channels/email.json

This switches Stackdriver's email notification channel to use auth user email for dev clusters.
Unfortunately Terragrunt interpolations [are not supported](https://github.com/gruntwork-io/terragrunt#interpolation-syntax) in module configuration block, so I had to add condition on `env` directly into `gcp-stackdriver-monitoring` module.
I also used `alerts+ENV@raisingthefloor.org` instead of `alerts+DOMAIN_NAME@raisingthefloor.org` to set notification email for all environments on Terragrunt level.

[GPII-3516]: Use auth user email for Stackdriver notifications

---

gcp/modules/gke-cluster/main.tf

```
1 error(s) occurred:
* module.gke_cluster.google_container_cluster.cluster-regional: 1 error(s) occurred:
* google_container_cluster.cluster-regional: googleapi: Error 400: Master version "1.11.3-gke.18" is unsupported., badRequest
```

Bump k8s version

---

gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/k8s_snapshots_errors.json

It takes about half of the alignment period for the policy to cool down.  
So, increasing duration threshold to 10 minutes would've been enough, but I decided to add another 5 mins on top of that.
This is the simplest way I can think of to make the policy skip intermittent errors, but still fire in case errors keep appearing in logs.

[GPII-3516]: Update k8s_snapshots_errors policy

---

common/modules/gcp-project/main.tf

`iamcredentials.googleapis.com` and `iam.googleapis.com` are tightly
coupled. Disabling one disables the other and missing one of
these causes never-ending Terraform change loop.
```bash
$gcloud services list | grep iam
iam.googleapis.com                      Identity and Access Management (IAM) API
iamcredentials.googleapis.com           IAM Service Account Credentials API
$ gcloud services disable iamcredentials.googleapis.com
Operation "operations/acf.635afed9-2459-4af0-b45a-6e0911780de1" finished successfully.
$ gcloud services list | grep iam
$ 
```

GPII-3606: Fix flapping iam services

---

common/modules/gcp-project/main.tf

This PR adds missing IAM roles for Google services. These are required for GKE to work properly.
For more details how did this happen see https://issues.gpii.net/browse/GPII-3609.

GPII-3609: Add missing Google services IAMs

---

gcp/README.md
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/couchdb_prometheus_exporter_exports_metric.json
shared/rakefiles/stackdriver.rb

Thanks to Sergey (and Stepan) for helping me find an alerting policy that worked in spite of Stackdriver weirdness.
How I tested:
* Deploy alerting policy with `rake`.
* Deploy again and see that policy is not updated.
* `helm delete --purge couchdb-prometheus-exporter`
* See that alert is triggered after 5 minutes of no metrics.
* `rake` to re-deploy alerting couchdb-prometheus-exporter.
* See that alert recovers when metrics return.

GPII-3394 Alert if couchdb metrics aren't making it to Stackdriver.

---

gcp/modules/couchdb/main.tf

This adds very simple timeout to `kubectl delete pvc` to prevent this getting stuck forever - (see [GPII-3601](https://issues.gpii.net/browse/GPII-3601)).

GPII-3601: Add timeout to kubectl delete for PVCs

---

gcp/modules/gcp-stackdriver-lbm/main.tf
gcp/modules/gcp-stackdriver-monitoring/main.tf
shared/rakefiles/stackdriver.rb

Changed Stackdriver client to prevent it from leaving scary stack traces in CI logs.
Changed shell code to retry only in case of deadline exceeded errors.

[GPII-3610]: Rescue Google::Gax::RetryError in Stackdriver client

---

shared/rakefiles/test.rake

This PR:
- fixes issue with retry count being one off when waiting for Locust pod deletion
- also reorders checks so that the loop behaves imho more as expected, in particular: 
- If the retry limit has been reached, exit without printing `Waiting for...` message
-  changed the test to more "defensive", less prone to infinite loops, `-gt` instead of `==`.

GPII-3637: Fix retry loop for Locust pod termination

---

gcp/modules/gke-cluster/main.tf

I did not re-enable cluster destroy protection after GPII-3568, which did not help re. recent prod cluster destroy issue, re-enabling here.

Re-enable cluster destroy protection

---

gcp/modules/helm-initializer/main.tf

This is alternative to https://github.com/gpii-ops/gpii-infra/pull/268.
Corresponding exekube part: https://github.com/gpii-ops/exekube/pull/35.

[GPII-3625]: Remove tiller_wait_period from helm-initializer

---

gcp/modules/locust/client.rb
gcp/modules/locust/swarm.tf

This PR fixes original infinite loop when sending Locust stats to Stackdriver error and couple of subsequently discovered issues with the shell & ruby code in the locust module:
- Refactor and fix infinite loop error
- Fix shell 'unknown operand' error caused by using unquoated variables
- Fix jq 'null (null) number required' error for median_response_time
- Add catch for ruby Google::Gax::RetryError ruby error
- Fix undefined method pop for nil:NilClass error in ruby client
It's not trying to solve the problem of locust not accepting Let's encrypt staging cert, this will be handled in another PR.

Fix infinite loop and other shell & ruby code issues in locust module

---

gcp/README.md
shared/rakefiles/entrypoint.rake

Corresponding exekube PR: https://github.com/gpii-ops/exekube/pull/36.

[GPII-3616]: Fix for deploy_module / destroy_module tasks to ignore module dependencies

---

shared/charts/locust/values.yaml

This moves us to our build of Locust Docker image. Main reasons being:
- Support for Let's Encrypt staging certs
- Improved security (update versions and get rid of known vulnerabilities of current image)
See https://github.com/gpii-ops/docker-image-locust/pull/1 for more details.
Dependencies:
- https://github.com/gpii-ops/docker-image-locust/pull/1 PR needs to be merged first.
- tag `0.9.0-gpii.0` has to be created (which will trigger the build of docker image with given tag)
The new image has been tested using `rake test_flowmanager` and `rake test_preferences`.

GPII-3649: Move to our build of locust image with LE Staging certificates

---

shared/charts/locust/values.yaml

Some minor changes on Locust image (see https://github.com/gpii-ops/docker-image-locust/pull/2 for details).

Bump locust image to 0.9.0-gpii.1

---

gcp/live/dev/k8s/cluster/terraform.tfvars

Reverts gpii-ops/gpii-infra#283.
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/157507990

[GPII-3697]: Revert "Use n1-highcpu-4 nodes for dev clusters"

---

shared/rakefiles/xk_util.rake

This PR enables the setting of some TF_VAR env variables needed by the `grant_owner_roles` and `revoke_owner_roles` tasks

[GPII-2802] Add dependency to set TF_VAR_auth_user_email variable

---

aws/modules/deploy/charts/values/cert-manager.erb

This makes new cert-manager work on AWS too. Missed this in #288

GPII-3701: Fix new cert-manager on AWS

---

aws/modules/deploy/charts/values/cert-manager.erb

This fixes the issue of non-working cert-manager on AWS by downgrading to `v0.5.2`. This seems to be latest working version, newer versions use newer version of Kubernetes client library that is not compatible with 1.8 API (the Kube version we're running on AWS).

GPII-3701: Fix new cert-manager on AWS - downgrade to 0.5.2

---

shared/charts/cert-manager/README.md
shared/charts/cert-manager/charts/webhook/templates/pki.yaml
shared/charts/cert-manager/requirements.lock
shared/charts/cert-manager/templates/00-namespace.yaml
shared/charts/cert-manager/templates/challenge-crd.yaml
shared/charts/cert-manager/templates/clusterissuer-crd.yaml
shared/charts/cert-manager/templates/issuer-crd.yaml
shared/charts/cert-manager/templates/order-crd.yaml
shared/charts/cert-manager/templates/rbac.yaml
shared/charts/cert-manager/values.yaml

This PR:
- Adds missing CRDs (`challenges` and `orders`). *I missed this previously because the upstream chart moved to manual CRD management but left the old CRD code, without the new CRDs, in the chart itself.*
- Updates CRDs to the ones from 0.6.1 (previously they stayed on some old version)
- Syncs other minor changes from 0.6.1 chart (webhook/pki, resources, rbac finalizers)
Another issue popped up - our tests do not test https for dev environments, that's also why this was missed, it will be solved as part of https://issues.gpii.net/browse/GPII-3668.

Fix issue with missing CRDs in cert-manager

---

.gitlab-ci.yml
common/modules/aws-gcp-dns/main.tf
common/modules/gcp-project/main.tf
gcp/README.md
gcp/live/dev/infra/network/terraform.tfvars
gcp/live/dev/k8s/cluster/terraform.tfvars
gcp/live/dev/k8s/stackdriver/export/terraform.tfvars
gcp/live/dev/secret-mgmt/terraform.tfvars
gcp/live/prd/infra/network/terraform.tfvars
gcp/live/prd/k8s/cluster/terraform.tfvars
gcp/live/stg/infra/network/terraform.tfvars
gcp/live/stg/k8s/cluster/terraform.tfvars
gcp/modules/gcp-secret-mgmt/main.tf
gcp/modules/gcp-stackdriver-export/main.tf
gcp/modules/gke-cluster/main.tf
gcp/modules/gke-network/main.tf
shared/rakefiles/entrypoint.rake
shared/rakefiles/tests/spec/vars_spec.rb
shared/rakefiles/vars.rb

Summary of changes:
* Use single `TF_VAR_infra_region` variable to set region for different infra components.
* Drop deprecated `additional_zones` parameter from `gke-cluster` module.
* Use 3-node `n1-highcpu-8` clusters for stg and prd.
* Use 3-node `n1-highcpu-4` clusters for dev.
* Comment and README updates.
Deployment plan:
There is a chance that switching region is not going to help with resource exhaustion issue too (#284), because initially I tried `us-west1` and got the same "Google Compute Engine does not have enough resources available" error.

[GPII-3697]: Use us-east1 for dev clusters, various fixes

---

gcp/modules/locust/swarm.tf

It takes ~5 retries before the first Locust workers show up, so increasing to 20 seems reasonable.

GPII-3740: Increase retries.

---

gcp/modules/gke-cluster/main.tf

This PR installs Istio GKE Add-on. 
_Note: This will not change behaviour of existing application in any way, as Istio sidecar has to be injected manually or by labelling the namespace with `istio-injection=enabled`._
Requires gpii-ops/exekube/pull/44.

GPII-3670: Enable Istio add-on

---

gcp/README.md

for better discoverability, and because the error messages if your Workspace is not set up is
not very helpful.
A couple developers hit this during initial GCP setup.

GPII-3590: Move one-time Stackdriver Workspace setup to Getting Started section

---

gcp/PERMISSIONS.md
shared/rakefiles/xk_infra.rake

For convenience we attached the "viewer" role to the cloud-admin group

GPII-2802 - Add viewer role to the cloud-admin group

---

.gitlab-ci.yml
gcp/README.md
shared/rakefiles/entrypoint.rake
shared/rakefiles/xk_util.rake

There's a lot that can be tweaked here (running more/fewer/different commands? do we want to wait 30s * N commands if the cluster is completely broken? `-o json`?) but here is a first pass.
The `-n locust` commands are probably not very useful until I reorganize destruction (part of my plan for GPII-3756).
Sample output from stg (because I don't have a dev cluster up ATM):
```
[tyler@toaster:~/rtf/gpii-infra/gcp/live/stg]$ rake display_cluster_state
docker-compose run --rm xk rake display_cluster_state
gcloud config set project $TF_VAR_project_id
Updated property [core/project].
**************
Cluster state:
**************
timeout -t 30 kubectl -n gpii get all -o wide
NAME                                                READY     STATUS      RESTARTS   AGE       IP           NODE …
```

GPII-3756: display_cluster_state

---

gcp/live/dev/k8s/gpii/flowmanager/terraform.tfvars
gcp/live/dev/k8s/gpii/preferences/terraform.tfvars
gcp/live/prd/k8s/gpii/flowmanager/terraform.tfvars
gcp/live/prd/k8s/gpii/preferences/terraform.tfvars
gcp/live/stg/k8s/gpii/flowmanager/terraform.tfvars
gcp/live/stg/k8s/gpii/preferences/terraform.tfvars
gcp/modules/gpii-flowmanager/main.tf
gcp/modules/gpii-flowmanager/values.yaml
gcp/modules/gpii-preferences/main.tf
gcp/modules/gpii-preferences/values.yaml
shared/charts/gpii-flowmanager/templates/ingress.yaml
shared/charts/gpii-flowmanager/values.yaml
shared/charts/gpii-preferences/templates/ingress.yaml
shared/charts/gpii-preferences/values.yaml
shared/charts/locust/values.yaml
shared/rakefiles/test.rake

This PR:
- Bumps Locust image to new build - `0.9.0-gpii.2` - this resolves some issues with LE Staging certs
- Moves all services to HTTPS only (in all envs) and removes code related to http support
- this also means that tests in dev will be run against https too

Move services to Https only

---

.gitlab-ci.yml

This reverts commit df12b352666bff6389778539c18d9eb7420fdda7.
Back to `us-east1` in the light of very global KMS 🌎

Revert "Try us-east4 for dev clusters"

---

.gitlab-ci.yml
gcp/README.md
shared/rakefiles/xk_util.rake

EDIT: Tested this in CI: https://gitlab.com/gpii-ops/gpii-infra/pipelines/49777249. It failed due to unrelated reasons, but the logic looks correct so far (destroyed things first, continuing in spite of failure; ran display_cluster_state when rake failed, then exited).

GPII-3756: Don't destroy env after failure.

---

.gitlab-ci.yml
shared/rakefiles/ci.rake
shared/rakefiles/test.rake

Per Stepan's suggestion in https://github.com/gpii-ops/gpii-infra/pull/314, I moved the CI logic for dev/ephemeral clusters into rake. Hopefully this new version is easier to understand.
The stg/prd workflow is pretty different and not as hard to read (fewer commands overall, fewer compound commands) so I left it alone.
I ran a few tests from my machine. It's hard to exercise all of the different permutations, but in general this seems to be running, aborting, and continuing as I expect.

GPII-3756: Add destroy_and_deploy_ci.

---

common/modules/gcp-project/main.tf
common/modules/gcp-project/service_accounts.tf
gcp/modules/gke-cluster/main.tf
shared/charts/couchdb/Chart.yaml
shared/charts/couchdb/templates/pod_disruption_budget.yaml
shared/charts/gpii-flowmanager/Chart.yaml
shared/charts/gpii-flowmanager/templates/pod_disruption_budget.yaml
shared/charts/gpii-preferences/Chart.yaml
shared/charts/gpii-preferences/templates/pod_disruption_budget.yaml

This PR is overarching for the move over to using Node Pool to manage instances within GKE Clusters. The actual rollout is split into 2 phases (to reduce complexity and provide no-downtime deployment).
This is a prerequisite for deploying Service Account Assigner (and moving over to ACME DNS challenge and deploying Istio).
The whole Node Pool rollout consists of following steps and corresponding PRs (in order):
This adds support for Node Pool in exekube.
This creates Primary Node pool with instances.
This removes any running workload from old "Default" nodes.
```console
old_nodes=($(kubectl get nodes -o name | grep default-pool))
for node in ${old_nodes[*]}; do
kubectl cordon "${node}"
done
for node in ${old_nodes[*]}; do
kubectl drain --ignore-daemonsets --delete-local-data=true …
```

Node Pool - phase 1

---

gcp/modules/gke-cluster/main.tf

This should hopefully fix the issue with missing credentials error in CI.

GPII-3419: Fix missing credentials for google provider error

---

common/modules/gcp-project/main.tf
common/modules/gcp-project/service_accounts.tf
gcp/modules/gke-cluster/main.tf
shared/charts/couchdb/Chart.yaml
shared/charts/couchdb/templates/pod_disruption_budget.yaml
shared/charts/gpii-flowmanager/Chart.yaml
shared/charts/gpii-flowmanager/templates/pod_disruption_budget.yaml
shared/charts/gpii-preferences/Chart.yaml
shared/charts/gpii-preferences/templates/pod_disruption_budget.yaml

This is 2nd part of moving over to Node Pools to manage nodes of GKE Clusters
It's part of the story described in #327.
**This PR**:
- Removes default GKE Cluster Node Pool (f6ffdbd)
- Removes permissions for default Compute service account (934a1bc)
This PR should be merged only after gpii-ops/exekube#47, #327 and gpii-ops/exekube#48. See #327 for more details.

Node pool - phase 2

---

common/modules/gcp-project/main.tf
common/modules/gcp-project/service_accounts.tf
gcp/live/dev/k8s/kube-system/k8s-snapshots/terraform.tfvars
gcp/live/dev/k8s/kube-system/service-account-assigner/terraform.tfvars
gcp/live/prd/k8s/kube-system/k8s-snapshots/terraform.tfvars
gcp/live/prd/k8s/kube-system/service-account-assigner/terraform.tfvars
gcp/live/stg/k8s/kube-system/k8s-snapshots/terraform.tfvars
gcp/live/stg/k8s/kube-system/service-account-assigner/terraform.tfvars
gcp/modules/k8s-snapshots/main.tf
gcp/modules/k8s-snapshots/service_account_iam.tf
gcp/modules/k8s-snapshots/templates/values.yaml.tpl
gcp/modules/k8s-snapshots/values.yaml
gcp/modules/service-account-assigner/main.tf
gcp/modules/service-account-assigner/service_account_iam.tf
gcp/modules/service-account-assigner/templates/values.yaml.tpl
shared/charts/k8s-snapshots/Chart.yaml
shared/charts/k8s-snapshots/README.md
shared/charts/k8s-snapshots/templates/deployment.yaml
shared/charts/k8s-snapshots/values.yaml
shared/charts/service-account-assigner/.helmignore
shared/charts/service-account-assigner/Chart.yaml
shared/charts/service-account-assigner/README.md
shared/charts/service-account-assigner/templates/_helpers.tpl
shared/charts/service-account-assigner/templates/daemon_set.yaml
shared/charts/service-account-assigner/templates/role.yaml
shared/charts/service-account-assigner/templates/role_binding.yaml
shared/charts/service-account-assigner/templates/service_account.yaml
shared/charts/service-account-assigner/values.yaml

This PR deploys GKE K8s Service Account assigner (https://github.com/imduffy15/k8s-gke-service-account-assigner) that allows assigning of GCP service accounts directly to individual pods via acting as a proxy in a path to GCP metadata service. *(This is prerequisite for moving over to DNS based ACME challenge for obtaining certificates (and Istio).)*
This PR also makes K8s-snapshots use dedicated service account, as this allows us to drop `storageAdmin` role from the default node service account.
This PR depends on gpii-ops/docker-image-service-account-assigner#2 and gpii-ops/k8s-gke-service-account-assigner#1.
This PR:
- Adds Service Account assigner Helm chart
- Adds and deploys service-account-assigner Terraform module
- Adds dedicated service account for k8s-snapshots
- Adds support …

Service Account assigner

---

gcp/live/dev/k8s/kube-system/k8s-snapshots/terraform.tfvars
gcp/live/prd/k8s/kube-system/k8s-snapshots/terraform.tfvars
gcp/live/stg/k8s/kube-system/k8s-snapshots/terraform.tfvars

This PR is a quick fix to [GPII-3824 - No disk snapshots in dev environments](https://issues.gpii.net/browse/GPII-3824).
We avoid the issue of `k8s-snapshots` not picking up changes on existing volumes (ie. added annotations) by deploying `k8s-snapshots` only after `couchdb` and it's volumes have been created and annotated.

GPII-3824: Fix missing snapshots in dev environments

---

common/modules/gcp-project/main.tf

The CI account needs `iam.serviceAccounts.setIamPolicy` permission on the Service Accounts within the project re. the service-account-assigner change, therefore `roles/iam.serviceAccountAdmin` role.

GPII-3793: Add missing permission for the CI accounts

---

common/modules/gcp-project/main.tf

Looks like we need both `User` & `Admin` roles because of `iam.serviceAccounts.actAs`.

GPII-3793: Add missing permission for the CI accounts #2

---

common/modules/gcp-project/main.tf
shared/rakefiles/xk_infra.rake

This is missing documentation for Security Findings Review process and manual scans creation, but I would prefer to merge this (so APIs stop getting disabled every time CI runs) and address missing pieces in separate PR.

[GPII-3642]: Enable command center and web scanner APIs

---

common/modules/gcp-project/main.tf
common/modules/gcp-project/service_accounts.tf
gcp/live/dev/k8s/kube-system/cert-manager/terraform.tfvars
gcp/live/prd/k8s/kube-system/cert-manager/terraform.tfvars
gcp/live/stg/k8s/kube-system/cert-manager/terraform.tfvars
gcp/modules/cert-manager/main.tf
gcp/modules/cert-manager/service_account_iam.tf
gcp/modules/cert-manager/templates/values.yaml.tpl
gcp/modules/cert-manager/values.yaml
gcp/modules/gpii-flowmanager/main.tf
gcp/modules/gpii-flowmanager/templates/values.yaml.tpl
gcp/modules/gpii-preferences/main.tf
gcp/modules/gpii-preferences/templates/values.yaml.tpl
shared/charts/gpii-flowmanager/Chart.yaml
shared/charts/gpii-flowmanager/README.md
shared/charts/gpii-flowmanager/templates/certificate.yaml
shared/charts/gpii-flowmanager/templates/issuer.yaml
shared/charts/gpii-flowmanager/values.yaml
shared/charts/gpii-preferences/Chart.yaml
shared/charts/gpii-preferences/README.md
shared/charts/gpii-preferences/templates/certificate.yaml
shared/charts/gpii-preferences/templates/issuer.yaml
shared/charts/gpii-preferences/values.yaml

This PR moves Let's Encrypt ACME certificate validation to DNS challenge (prereq to Istio deployment). It also addresses couple of related issues (see [GPII-3781](https://issues.gpii.net/browse/GPII-3781) for detials ).
Changes introduced:
- Change ACME validation method to `dns01`
- Add dedicated service account for `cert-manager` for DNS challenge
- Move `cert-manager` (Cluster)Issuer inside `gpii-flowmanager` and `gpii-preferences` charts
- Change email used for Let's encrypt to `ops@`, or individual user emails for non-prod/stg envs
Since current implementation of ClusterIssuer will leave resources behind, cleanup should be done in non-ephemeral envs:
```
kubectl delete clusterissuer letsencrypt-production
kubectl delete clusterissuer letsencrypt-production
```

Move Let's Encrypt certificate validation to DNS challenge

---

gcp/modules/cert-manager/main.tf

Missed the provider definition (again)... which fails on CI.

GPII-3781: Add missing google provider definition

---

gcp/modules/cert-manager/main.tf

Looks like previously created resource is in a state and needs these credentials to refresh, even though it's been removed by reverting the previous change.

Fix reverted dns change - stuck state

---

.gitlab-ci.yml
gcp/README.md
shared/rakefiles/entrypoint.rake
shared/rakefiles/xk_util.rake

This should be helpful for developers, while we think on better long-term approach.

[GPII-3841]: Add display_universal_image_info task

---

ONE-TIME-SETUP.md
gcp/README.md

I could not decide if this belongs to readme or maybe worth starting another document on security principles?
Should our [weekly infra metrics review process](https://pad.gpii.net/mypads/?/mypads/group/gpii-infrastructure-standups-lix4njm/pad/view/key-metrics-for-infrastructure-pc1g4nnd) (which I updated in the pad) be also documented here?

[GPII-3642]: Add security scans configuration instructions into README

---

common/modules/gcp-project/main.tf
common/modules/gcp-project/service_accounts.tf
shared/charts/locust/values.yaml

This is "fix" for failing Locust tests after cluster creation. Atm. we don't wait for or check that the services are ready, but simply rely that they will be available by the time we run the Locust test.
This PR adds a wait that the targeted service needs to be reachable from within the pods before starting the test.
Depends on https://github.com/gpii-ops/docker-image-locust/pull/4
Details about my investigation can be found at https://gist.github.com/stepanstipl/6eb26d942d7ded09f741a0b9f3677de1.
TL;DR:
- Issue is related to DNS resolution
- I wasn't yet able to pin it down to specific setting, but looks like issue with negative caching somewhere in the DNS resolution path
- Issue happens only on newly-created cluster, if the tests are run right after cluster setup, otherwise it does not …

GPII-3843: Wait for service to be reachable before starting the Locust tests

---

shared/rakefiles/xk_infra.rake

Follow up to #348. I must have manually enabled the API during testing in common-stg.

GPII-3641: Add containerregistry to common projects.

---

gcp/modules/gpii-flowmanager/dns.tf
gcp/modules/gpii-flowmanager/main.tf
gcp/modules/gpii-preferences/dns.tf
gcp/modules/gpii-preferences/main.tf

This is to resolve the issue with DNS challenge and failing wildcard DNS/locust tests [GPII-3843](https://issues.gpii.net/browse/GPII-3843).
The observed behavior is "by design", although not all DNS servers implement this consistently. There's a whole RFC just to clarify wildcard records - https://tools.ietf.org/html/rfc4592. This behavior is usually referenced as "Empty Non-terminals".
This PR:
- Creates individual specific DNS records for both preferences and flowmanager, which resolves the problem of non-working wildcard when `_acme-challenge` TXT record exists. More about this can be found in my notes on investifaton - https://gist.github.com/stepanstipl/6eb26d942d7ded09f741a0b9f3677de1.
- Reduces TTL to 300s - in my experience shorter TTL increases agility when any infra changes are …

GPII-3843: Create individual DNS records for preferences & flowmanager

---

gcp/README.md

Update the load of the data section in the README
[Rendered version](https://github.com/gpii-ops/gpii-infra/blob/f00b77119210efde4f9dabca8c5688b6492378c3/gcp/README.md#load-the-data-into-a-cluster)

GPII-3867 - Update load data section

---

gcp/live/dev/k8s/kube-system/cert-manager/terraform.tfvars
gcp/live/prd/k8s/kube-system/cert-manager/terraform.tfvars
gcp/live/stg/k8s/kube-system/cert-manager/terraform.tfvars
gcp/modules/cert-manager/main.tf
gcp/modules/cert-manager/service_account_iam.tf
gcp/modules/cert-manager/templates/values.yaml.tpl
gcp/modules/cert-manager/values.yaml
gcp/modules/gpii-flowmanager/main.tf
gcp/modules/gpii-flowmanager/templates/values.yaml.tpl
gcp/modules/gpii-preferences/main.tf
gcp/modules/gpii-preferences/templates/values.yaml.tpl
shared/charts/gpii-flowmanager/Chart.yaml
shared/charts/gpii-flowmanager/README.md
shared/charts/gpii-flowmanager/templates/certificate.yaml
shared/charts/gpii-flowmanager/templates/issuer.yaml
shared/charts/gpii-flowmanager/values.yaml
shared/charts/gpii-preferences/Chart.yaml
shared/charts/gpii-preferences/README.md
shared/charts/gpii-preferences/templates/certificate.yaml
shared/charts/gpii-preferences/templates/issuer.yaml
shared/charts/gpii-preferences/values.yaml

This is just updated original  PR #342, since we solved the issue with wildcard DNS. CP of original text:
This PR moves Let's Encrypt ACME certificate validation to DNS challenge (prereq to Istio deployment). It also addresses couple of related issues (see [GPII-3781](https://issues.gpii.net/browse/GPII-3781) for detials ).
Changes introduced:
- Change ACME validation method to `dns01`
- ~Add dedicated service account for `cert-manager` for DNS challenge~ - this has already been merged in
- Move `cert-manager` (Cluster)Issuer inside `gpii-flowmanager` and `gpii-preferences` charts
- Change email used for Let's encrypt to `ops@`, or individual user emails for non-prod/stg envs
Since current implementation of ClusterIssuer will leave resources behind, cleanup should be done in non-ephemeral …

Move Let's Encrypt certificate validation to DNS challenge  #2

---

gcp/PERMISSIONS.md
shared/rakefiles/entrypoint.rake
shared/rakefiles/xk_util.rake

This PR changes `:grant_owner_role`, `:revoke_owner_role` tasks into tasks that along with owner role in current project grant / revoke org-level super permissions (which are required for SCC administration operations).
The downside of current implementation is that now there is no way to automatically revoke org-level permissions, since we do not enforce org-level IAM policy. I'll think what can be done to improve this.

[GPII-3642]: Add :grant_org_admin, :revoke_org_admin tasks

---

shared/versions.yml

This PR bumps locust image from gpii-ops/docker-image-locust/pull/6
This is an attempt to solve the issue with a high number of failing CI builds, due to the slow max_response_time after moving to the DNS challenge, by waiting for multiple consecutive good replies from the service before starting the test.
Depends on gpii-ops/docker-image-locust/pull/6

GPII-3883: Locust - wait for several successful responses before moving on

---

CI-CD.md
gcp/README.md

Goes with https://github.com/gpii-ops/gpii-version-updater/pull/17.

GPII-3861: Update docs for gpii-version-updater changes.

---

shared/rakefiles/tests/spec/vars_spec.rb
shared/rakefiles/vars.rb

This was part of #370 but I ran into it while deploying #368, so I've extracted it into its own PR to merge separately.

GPII-3641: Handle tags that look like floats (or integers)

---

shared/rakefiles/entrypoint_common.rake
shared/rakefiles/xk_infra.rake

Summary of changes:
* Every time `:apply_common_infra` runs, it invokes `:set_org_perms` that
1. Removes all roles from individual user accounts (to revoke perms granted to operators by `:grant_org_admin`).
1. For common SA, cloud-admin group and Eugene's account: it ensures that only expected set of permissions is present, removes all unexpected roles.
* Refactored `:refresh_common_infra` and related tasks.

[GPII-3865]: Improve the way we set organization-level permissions

---

shared/rakefiles/ci.rake
shared/rakefiles/xk_config.rake

I had to revert #366, because it turned out that I was testing the code with rake `:configure_serviceaccount` auth, but even if you have SA key downloaded, it needs to be activated, otherwise `gcloud` calls will keep using credentials retrieved by `auth login` (therefore changing IAM and set of permissions).

[GPII-3885]: Add :activate_serviceaccount task

---

gcp/modules/couchdb-prometheus-exporter/main.tf
gcp/modules/couchdb-prometheus-exporter/values.yaml
shared/charts/couchdb-prometheus-exporter/README.md
shared/charts/couchdb-prometheus-exporter/templates/deployment.yaml
shared/charts/couchdb-prometheus-exporter/values.yaml
shared/charts/nginx-ingress/Chart.yaml
shared/charts/nginx-ingress/OWNERS
shared/charts/nginx-ingress/README.md
shared/charts/nginx-ingress/ci/psp-values.yaml
shared/charts/nginx-ingress/templates/_helpers.tpl
shared/charts/nginx-ingress/templates/controller-daemonset.yaml
shared/charts/nginx-ingress/templates/controller-deployment.yaml
shared/charts/nginx-ingress/templates/controller-metrics-service.yaml
shared/charts/nginx-ingress/templates/controller-poddisruptionbudget.yaml
shared/charts/nginx-ingress/templates/controller-service.yaml
shared/charts/nginx-ingress/templates/controller-servicemonitor.yaml
shared/charts/nginx-ingress/templates/controller-stats-service.yaml
shared/charts/nginx-ingress/templates/default-backend-deployment.yaml
shared/charts/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
shared/charts/nginx-ingress/templates/default-backend-service.yaml
shared/charts/nginx-ingress/templates/podsecuritypolicy.yaml
shared/charts/nginx-ingress/templates/role.yaml
shared/charts/nginx-ingress/templates/scoped-clusterrole.yaml
shared/charts/nginx-ingress/templates/scoped-clusterrolebinding.yaml
shared/charts/nginx-ingress/values.yaml
shared/versions.yml

This PR replaces #370 -- there is nothing new to review. It has the contents of #370, rebased onto master now that #367 and #368 (and version-updater companion PRs) are merged, minus #372 (which was merged separately while merging #367 and #368).
* GPII-3641: Replace busybox with alpine for couchdb init container
* ~GPII-3871: Re-run port-forward each time when checking membership for couchdb.finish_cluster~ --> #377 
* GPII-3856 Update couchdb-prometheus-exporter's prometheus-to-sd to the latest, 0.5.1
* GPII-3857: Update nginx-ingress to the latest 0.21.1 and (for fun) update the chart with latest from upstream.
* ~GPII-3846: Update couchdb to 2.3.0 and (for fun) couchdb-statefulset-assembler to 1.2.0.~ --> #376 
Additional testing info:
* This deploy and all deploys happen with …

GPII-3641 GPII-3856 GPII-3857 Image updates

---

shared/versions.yml

Separated from https://github.com/gpii-ops/gpii-infra/pull/373.

GPII-3846: Upgrade to couchdb 2.3

---

gcp/modules/gpii-preferences/main.tf

Terraform needs the provider definition in order to delete the existing resource.

GPII-3221: Fix missing provider definition needed to remove resources

---

shared/rakefiles/xk_infra.rake

This role is required to [link projects to billing account](https://github.com/gpii-ops/gpii-infra/blob/master/shared/rakefiles/xk_infra.rake#L85-L86).

[GPII-3865]: Add missing billing user role to common SA

---

shared/rakefiles/xk_infra.rake

This [should allow](https://cloud.google.com/iam/docs/understanding-roles) read access to scans and scan runs, plus the ability to start scans without need to grant project admin.

[GPII-3890]: Add missing cloud security scanner roles to cloud-admin account

---

gcp/live/dev/locust/istio/terraform.tfvars
gcp/live/dev/locust/swarm/terraform.tfvars
gcp/live/prd/locust/istio/terraform.tfvars
gcp/live/prd/locust/swarm/terraform.tfvars
gcp/live/stg/locust/istio/terraform.tfvars
gcp/live/stg/locust/swarm/terraform.tfvars
gcp/modules/locust-istio/main.tf
gcp/modules/locust/swarm.tf
shared/charts/locust/Chart.yaml
shared/charts/locust/templates/_helpers.tpl
shared/charts/locust/templates/egress-service-entry.yaml
shared/charts/locust/templates/master-deploy.yaml
shared/charts/locust/values.yaml
shared/rakefiles/xk.rake

This is additional PR to the Istio series since we moved Preferences endpoint out of internet and the tests now run against the internal endpoint. Since we're moving that to Istio and enforcing mutual TLS auth, Locust wouldn't be able to connect unless running on Istio itself.
This PR moves Locust to Istio and should be merged before/together with https://github.com/gpii-ops/gpii-infra/pull/324.
This PR:
- Adds locust-istio module to create istio-enabled locust namespace
- Moves locust chart to Istio (liveness & readinees, egress service entry)
- Makes locust module work with Istio
- Adds temporary migration code for locust namespace
I have tried to do this without creating a new dedicated module just for the locust namespace, but wasn's successful due to Helm's inability to handle labels …

Istio phase 2.5 - Locust

---

shared/rakefiles/xk.rake

This was a leftover from trying to find a better solution for ns import in https://github.com/gpii-ops/gpii-infra/pull/388, and should have been removed.
(it shows only in non-ephemeral envs)

GPII-3671: Fix wrong tf import

---

gcp/docker-compose.yaml

This requires https://github.com/gpii-ops/exekube/pull/52

GPII-3745: Bump to 0.5.0-google_gpii.0.

---

.circleci/config.yml
.gitlab-ci.yml
common/docker-compose.yaml
common/modules/gcp-project/main.tf
gcp/README.md
gcp/docker-compose.yaml
gcp/modules/gke-cluster/main.tf
shared/rakefiles/entrypoint.rake
shared/rakefiles/tests/Gemfile
shared/rakefiles/tests/Gemfile.lock

More preparatory steps for using Binary Authorization in GKE. There are a few semi-related things in this PR:
* Some plumbing for binary authorization (see also https://github.com/gpii-ops/exekube/pull/53)
* Bump various references to use the new 0.5.1 exekube image
** I should have bumped some of these to 0.5.0 in #390; better late than never ;)
** DRY out image reference in CircleCI config. Tested using my fork -- all tests green there
* Remove `update_exekube`. It shouldn't be needed now that we're using 'immutable' tags
* Enable binary auth API

GPII-3860: Plumbing, 0.5.1

---

gcp/modules/gke-cluster/main.tf

This PR upgrades Kubernetes to 1.12. Main driver for this is garbage collector issue (see https://issues.gpii.net/browse/GPII-3903 for details). The current (follow K8s default version) logic is disabled, and should be re-enabled once 1.12 is available as default.
I have tested:
- Creating new cluster with 1.12
- Upgrading from current master (1.11) to 1.12
- Downgrade by manually deleting the cluster
Q&A:
- **Any changes to support on 1.12?**
During my testing (mainly running `rake test_preferences` and `test_flowmanager`, checking Stackdriver alerts), I did not observe any issues nor changes that would require any further action.
- **What does a rollback look like?**
Unfortunately downgrading a minor version is not supported GKE operation …

GPII-3909: Upgrade Kubernetes to 1.12

---

gcp/modules/gke-cluster/main.tf

This PR disables GKE default version skew check to prevent undesired minor version upgrades, until GKE rolls-out 1.12 as a default across all regions.
Ticket will be created to re-enable this.

GPII-3909: Disable default version upgrade check

---

gcp/modules/gpii-flowmanager/dns.tf

This is another try on reverted https://github.com/gpii-ops/gpii-infra/pull/324 after resolving the missing ingress-gateway certs/Kube garbage collector issue (GPII-3903) by upgrading to 1.12.
This PR is part of Istio rollout series described in #322 (and should be merged only after #322 and #323).
**This PR** changes external DNS records to IngressGateway.
Included changes:
- Creates individual DNS records for services and points those to Istio IngressGateway (e76578d)
After deployment, verify that:
1. [ ] Flowmanager still works
2. [ ] DNS record points to Istio IngressGateway

Istio phase 3 - try #2

---

.gitlab-ci.yml
shared/rakefiles/xk.rake

This PR fixes [GPII-3910 - Investigate and fix "Error loading state" - "The provided encryption key is incorrect" errors](https://issues.gpii.net/browse/GPII-3910) and removes temporary Istio migration scripts.
The issue was caused by a combination of the `terragrunt state pull` which would create the state-file if it didn't exist and running `rake rotate_tfstate_key` in stg/prd environments, which would rotate keys, but only for components under `k8s/` directory and not `locust/`. While there are other possible fixes, removing the unnecessary migration scripts is imho best course fo action.
This might cause issues to devs who still haven't upgraded, but both Istio and locust/Istio have been around for a while.
PR also fixes order of locust modules destroy - `locust/istio` module deletes …

Minor fixes & cleanup

---

shared/versions.yml

https://github.com/GPII/ci-service/pull/57 is merged. This PR uses that new tags created during universal builds.
FYI @klown flushtokens will need a similar change.

GPII-3919: Change to new universal tag system.

---

gcp/modules/gke-cluster/main.tf

Since Google seems to have updated default version in all regions (at least the ones we use - I've checked `us-central1`, `us-east1`, `us-east4`), we can re-enable the TF auto-version logic so that we're consistent with the default version and master auto-upgrade feature.

GPII-3913: Re-enable auto cluster version update

---

PRINCIPLES.md
shared/rakefiles/entrypoint.rake
shared/rakefiles/xk_util.rake

```
[tyler@toaster:~/rtf/gpii-infra/gcp/live/stg]$ rake display_cluster_state
...
timeout -t 30 kubectl -n istio-system get svc
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                                                                                                   AGE
istio-citadel            ClusterIP      10.18.24.50     <none>          8060/TCP,9093/TCP                                                                                                         65d
istio-egressgateway      ClusterIP      10.18.104.250   <none>          80/TCP,443/TCP                                                                                                            65d
istio-galley             ClusterIP      10.18.182.171   <none> …
```

GPII-3941: Fully-specified version vs floating patch version; init_registry uses alpine:3.9; add commands to display_cluster_state

---

gcp/modules/gpii-flowmanager/dns.tf
gcp/modules/gpii-flowmanager/main.tf

This PR adds a wait for Istio's ingress gateway IP to be allocated (before trying to retrieve it via TF's data source).
This also fixes error when running destroy on empty infrastructure.

GPII-3937: Wait for Istio ingress IP

---

common/docker-compose.yaml
gcp/docker-compose.yaml
shared/charts/gpii-preferences/Chart.yaml
shared/charts/gpii-preferences/templates/deployment.yaml

This PR upgrades exekube image to `gpii/exekube:0.6.0-google_gpii.0`. This upgrades Terraform, Terraform providers and other components, see https://github.com/gpii-ops/exekube/pull/56 for details.
This mainly fixes node_pool recreation due to metadata config ([GPII-3940](https://issues.gpii.net/browse/GPII-3940)) - see GoogleCloudPlatform/magic-modules#1507 for details.
Also included is a small formatting fix for preferences chart which was causing wrong yaml indentation and deployment spec validation fail with new helm.

GPII-3940: Exekube upgrade

---

gcp/modules/certmerge-operator-crd/main.tf

This is a bit of a long-shot to try to fix the Istio ingress-gateway-certs/garbage collector issue.
Due to the difficulty of reproducing this, I'm not able to confirm if it will fix the issue, but certainly shouldn't make anything worse. The cross-namespace GC seems to be un-intentional (although it's deleting the certs in our case) as per official docs - https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/, and there are a couple of issues related to this, mainly:
- https://github.com/kubernetes/kubernetes/pull/63386
- https://github.com/kubernetes/kubernetes/issues/65200
I originally didn't think this might be the cause, but after going through the issues above & some others opened against Kubernetes, I think it's worth a shot.
This PR moves the parent resource …

GPII-3903: Fix garbage-collector cross-namespace issue

---

shared/charts/couchdb-prometheus-exporter/Chart.yaml

This PR bumps version of CouchDB Prometheus exporter Chart to force redeployment with new labels (disabling istio sidecar) on non-ephemeral clusters.
This fixes issue of Prometheus exporter not starting.

GPII-3959: Fix for CouchDB prometheus exporter not starting

---

gcp/modules/locust/values.yaml
shared/charts/locust/Chart.yaml
shared/charts/locust/templates/_helpers.tpl
shared/charts/locust/templates/master-deploy.yaml
shared/charts/locust/templates/worker-svc.yaml

This PR is a try to fix the issue with failing tests, which is caused by Istio (race condition between podIP and adding inbound listener I believe, see https://issues.gpii.net/browse/GPII-3960 for more details). 
One of the "soft" requirements for Istio is that a pod must belong to at least one Kubernetes service even if the pod does NOT expose any port (see https://istio.io/docs/setup/kubernetes/prepare/requirements/ for details). This affects discovery and how & when Istio pushes info to pilot and other proxies, and I believe it might help in our case.
I've tested this, running tests with and without this fix in stg, and it seems to make a difference. But as I can't reproduce the issue reliably, I'm not 100% sure it will fix the issue.
Changes introduced in this PR:
- Change locust …

Istio pilot workaround

---

.gitlab-ci.yml
gcp/modules/gcp-stackdriver-lbm/main.tf
gcp/modules/gcp-stackdriver-lbm/resources/log_based_metrics/compute_firewalls.json
gcp/modules/gcp-stackdriver-lbm/resources/log_based_metrics/compute_firewalls_modify.json
gcp/modules/gcp-stackdriver-lbm/resources/log_based_metrics/compute_instances_insert.json
gcp/modules/gcp-stackdriver-lbm/resources/log_based_metrics/dns_modify.json
gcp/modules/gcp-stackdriver-lbm/resources/log_based_metrics/gke_cluster_create.json
gcp/modules/gcp-stackdriver-lbm/resources/log_based_metrics/iam_modify.json
gcp/modules/gcp-stackdriver-lbm/resources/log_based_metrics/servicemanagement_modify.json
gcp/modules/gcp-stackdriver-lbm/resources/log_based_metrics/stackdriver_alertpolicy_modify.json
gcp/modules/gcp-stackdriver-monitoring/main.tf
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/compute_firewalls_modify.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/compute_instances_insert.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/couchdb_prometheus_exporter_exports_metric.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/dns_modify.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/firewalls_activity.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/gke_cluster_create.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/iam_modify.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/servicemanagement_modify.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/stackdriver_alertpolicy_modify.json
shared/rakefiles/tests/spec/vars_spec.rb
shared/rakefiles/vars.rb

As it turned out after all my experiments with Forseti scanners – this is the most straightforward way to address the issue.
Since it is impossible to reliably distinguish between TF-managed and "rogue" instances, log-based metric and policy is configured to alert on all `compute.instances.insert` events. I don't think it is going to be a trouble for long-lived clusters (stg / prd), but it can potentially add some more alert noise for ephemeral clusters.

[GPII-2862]: Add log-based metrics and alert policies to notify on critical security events

---

shared/versions.yml

This is the second pull to add validation checks to various endpoints provided by the universal repository. 
This is the second pull, [the previous pull](https://github.com/gpii-ops/gpii-infra/pull/416) did not use a new enough version of the universal docker container.
This deployment does not require any special handling, there are no changes to data stored in CouchDB that would require a migration.  There are  no new containers, i.e. this is. just an update to the three containers provisioned from the universal container.
@cindyli can easily verify the change by:
1. Logging in to get auth credentials.
2. Using those credentials to attempt to submit an invalid payload to one of the secured endpoints, (settings GET, etc.).

GPII-3968: Updated to new enough version to pick up payload validation checks.

---

gcp/modules/locust/tasks/flowmanager.py
gcp/modules/locust/tasks/preferences.py

telugu's snapset was invalid under Tony's new validation scheme.
nvda is the largest snapset we currently have (10k).

GPII-3968: Replace telugu with nvda.

---

shared/versions.yml

We had a performance problem -- median response time during smoke test increased 10x.

GPII-3986: Roll back to before deployment started.

---

.gitlab-ci.yml
gcp/live/dev/k8s/istio/terraform.tfvars
gcp/live/prd/k8s/istio/terraform.tfvars
gcp/live/stg/k8s/istio/terraform.tfvars
gcp/modules/istio/hpa.tf
gcp/modules/istio/main.tf
shared/rakefiles/entrypoint.rake
shared/rakefiles/scripts/sync_gke_istio_state.sh
shared/rakefiles/xk.rake
shared/rakefiles/xk_config.rake

This PR adds management of Istio HPAs to make Istio deployment Highly Available. All the components are set to min 2 instances (while still allowing them to autoscale up to 5 - GKE's default), except for `istio-ingressgateway` which is set to 3 instances as this is component in the critical path accessed externally via the load-balancer and more instances give the gcp load-balancer health checks a bit more time to settle in situations like node auto-upgrade.
Unfortunately, as Istio components are created and managed by Google (via Kubernetes add-on manager), they have to be imported to Terraform state first, before being modified via Terraform.

Istio HA - HPAs

---

gcp/modules/gke-cluster/istio-sync.tf
gcp/modules/gke-cluster/main.tf
shared/rakefiles/scripts/sync_gke_istio_state.sh

This PR fixes issue we see in CI on ephemeral clusters:
```yaml
5 errors occurred:
* kubernetes_horizontal_pod_autoscaler.istio-policy: 1 error occurred:
* kubernetes_horizontal_pod_autoscaler.istio-policy: horizontalpodautoscalers.autoscaling "istio-policy" already exists
...
```
(see https://gitlab.com/gpii-ops/gpii-infra/-/jobs/236134449).
This is caused by Istio HPAs state not being synced between the initial cluster creation and the first run of `istio` module.
Not sure why I didn't catch this initially when testing the cluster creation scenario, but I was able to reproduce this in the local dev env and test the fix.

Istio HPA state sync fix

---

shared/rakefiles/xk_infra.rake

This PR adds back `roles/resourcemanager.projectCreator` which was removed as part of https://github.com/gpii-ops/gpii-infra/pull/380 PR and is causing fail when creating new environments:
```
1 error occurred:
* google_project.project: 1 error occurred:
* google_project.project: error creating project gpii-gcp-dev-duhrer (gpii-gcp-dev-duhrer): googleapi: Error 403: User is not authorized., forbidden. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission
```
(see https://gitlab.com/gpii-ops/gpii-infra/pipelines/67450122 for more).

Fix removed projectCreator role

---

gcp/README.md

I added this note during a meeting and now I'm committing it.
Please feel free to merge this whenever; I am confident it will not break anything :) but I didn't want to trigger a pipeline before going offline for a week.

Deploy plans should include a rollback plan.

---

gcp/live/dev/k8s/istio-gke-helper/terraform.tfvars
gcp/live/prd/k8s/istio-gke-helper/terraform.tfvars
gcp/live/stg/k8s/istio-gke-helper/terraform.tfvars
gcp/modules/istio-gke-helper/main.tf
shared/charts/istio-gke-helper/.helmignore
shared/charts/istio-gke-helper/Chart.yaml
shared/charts/istio-gke-helper/README.md
shared/charts/istio-gke-helper/templates/_helpers.tpl
shared/charts/istio-gke-helper/templates/pod_disruption_budget.yaml
shared/charts/istio-gke-helper/values.yaml

This PR introduces Pod Disruption Budget (PDBs) for Istio components. This should increase HA and help in situations like node pool upgrades by ensuring that no more than 1 instance of the critical Istio control plane components is down at a time.
Initially, I wanted to implement this via native TF provider, but it does not support PDBs at this moment, and therefore the new Helm chart and necessity of a separate module.  This cannot co-exist in istio module due to Terraform's inability to handle dynamic provider configuration for `import` command (even though the provider is not used for the actual resource import, helm_release & helm provider use data source dependent config). See hashicorp/terraform#17847 for details.

Istio PDBs

---

common/modules/aws-gcp-dns/main.tf

This PR is part of [GPII-3591](https://issues.gpii.net/browse/GPII-3591). This PR deletes the aws.gpii.net and aws.test1.gpii.net zones and their NS records in the parent domains.
Changes for common-stg
```
[...]
Refreshing Terraform state in-memory prior to plan...                                                                                                                                 
The refreshed state will be used to calculate this plan, but will not be                                                                                                              
persisted to local or remote state storage.                                                                                                                                           
google_dns_managed_zone.main: …
```

GPII-3591 - Delete the DNS AWS zones of the deprecated GPII AWS

---

gcp/README.md

Part of [GPII-2805](https://issues.gpii.net/browse/GPII-2805)
This PR adds the description of a periodically procedure applied to the `stg` environment of the infrastructure.
[Rendered version](https://github.com/gpii-ops/gpii-infra/blob/53d5aa9348fd01cea33e66f3203196631ea53be4/gcp/README.md#stg)

GPII-2805 - Add backup testing procedure to stg environment

---

gcp/modules/gke-network/main.tf

I've removed TF provider config block by mistake as part of cleaning up the **_mostly_** commented out `global-ip.tf` file (https://github.com/gpii-ops/gpii-infra/commit/0fa9460eb58128d3302aed618060d63091767204).

GPII-3952: Fix missing provider config block

---

shared/rakefiles/xk_util.rake

[GPII-3901](https://issues.gpii.net/browse/GPII-3901)
**Description of the fix**
It is not possible attach the owner role to an user of a different organization using the API:
https://cloud.google.com/iam/docs/understanding-roles#invitation_flow
It must be set using the console, and the user must accept the invitation.
A workaround could be to create manually a group with owner permissions and add the people to that group but it has two downsides from my point of view:
- hard to maintain the users of such group.
- it is not consistent along the rest of the projects of the organization.
Other option is to make the test org recognize the raisingthefloor.org users as organization users. But I don't know if that it is possible.
The editor role is almost the same as the owner but without:
- …

GPII-3901: Grant editor role for testing organization istead of owner role

---

.gitlab-ci.yml
gcp/modules/locust/swarm.tf
shared/rakefiles/test.rake

Existing implementation of `:test` task was a little backwards, destroying locust resources before instead of after the test, which caused various CI issues in case module and TF state was not destroyed separately.

[GPII-4003]: Fix :test task to properly destroy locust resources

---

gcp/live/dev/k8s/gpii/istio/terraform.tfvars
gcp/live/prd/k8s/gpii/istio/terraform.tfvars
gcp/live/stg/k8s/gpii/istio/terraform.tfvars

This is a small dependency fix I've missed in #444, after moving the "wait for Istio IP" logic to a `istio` module.
Fixes following CI error by extending the dependency chain - `k8s/gpii/flowmanager` -> `k8s/gpii/istio` ->  `k8s/istio`:
```
1 error occurred:
* google_dns_record_set.flowmanager-dns: Resource 'data.kubernetes_service.istio-ingressgateway' does not have attribute 'load_balancer_ingress.0.ip' for variable 'data.kubernetes_service.istio-ingressgateway.load_balancer_ingress.0.ip'
```

GPII-3970: Add dependency on parent Istio - wait for external IP

---

gcp/live/dev/k8s/gpii/couchdb-prometheus-exporter/terraform.tfvars
gcp/live/dev/k8s/gpii/couchdb/terraform.tfvars
gcp/live/prd/k8s/gpii/couchdb-prometheus-exporter/terraform.tfvars
gcp/live/prd/k8s/gpii/couchdb/terraform.tfvars
gcp/live/stg/k8s/gpii/couchdb-prometheus-exporter/terraform.tfvars
gcp/live/stg/k8s/gpii/couchdb/terraform.tfvars

Work on static istio ip (#444, #445) surfaced existing race condition between Terraform and Helm when creating `gpii` namespace. When Helm gets there first, following error happens:
```
1 error occurred:
* kubernetes_namespace.gpii: 1 error occurred:
* kubernetes_namespace.gpii: namespaces "gpii" already exists
```
This PR fixes this by making all the remaining modules (`couchdb` and `couchdb-prometheus-exporter`) depend on `gpii/istio` module, which creates the namespace.

GPII-3970: Fix gpii namespace creation race condition

---

shared/charts/locust/Chart.yaml
shared/charts/locust/templates/egress-virtual-service.yaml

Work on static Istio ip (#444, #445, #447) seems to have made existing Issue with failing flowmanager tests (ie. https://gitlab.com/gpii-ops/gpii-infra/-/jobs/249398218) significantly more frequent - now it happens almost on every run on ephemeral clusters.
I was unable to reproduce this reliably locally and also unable to reproduce on existing CI cluster - `rake test_flowmanager` on an existing cluster works fine (one left behind by failed CI run - ig. `dev-gitlab-runner` env). This is furthermore difficult since we don't keep the locust containers around anymore after the failed tests (after https://github.com/gpii-ops/gpii-infra/pull/437) so I was not able to verify if this is the very same underlying issue we used to see or a slightly different one.
Investigating issues @natarajaya …

GPII-3970: Try to fix failing flowmanager tests

---

shared/rakefiles/entrypoint.rake
shared/rakefiles/test.rake

CI skips `:destroy_tfstate` in `:test` for ephemeral clusters:
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/248496212
And here is the reason:
* `:test` tasks [are part of](https://github.com/gpii-ops/gpii-infra/blob/master/shared/rakefiles/ci.rake#L67-L68) `:destroy_hard_and_deploy_ci`
* `:destroy_tfstate` already being executed [as part of](https://github.com/gpii-ops/gpii-infra/blob/master/shared/rakefiles/entrypoint.rake#L141-L150) `:destroy_hard`
* So it needs to be reenabled again before invocation in `:test`
Also, there is no need to destroy locust state in `:destroy_hard` anymore.

[GPII-4003]: Clean up :destroy_hard, reenable :destroy_tfstate in :test

---

shared/versions.yml

This PR switches `service-account-assigner` to new version with changes from:
https://github.com/gpii-ops/k8s-gke-service-account-assigner/pull/2
Merge after:
https://github.com/gpii-ops/docker-image-service-account-assigner/pull/3

[GPII-3868]: Use gpii/service-account-assigner:0.0.3-gpii.0

---

common/modules/gcp-project/main.tf

This PR fixes missing permissions for the binary auth deployment.

GPII-3860: Fix missing permission for bin auth

---

.circleci/config.yml

No reason to run them, since AWS infra is no more.

GPII-3591: Remove aws-unit-tests from CircleCI config

---

gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/backup_exporter_errors.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/backup_exporter_snapshots.json

This PR fixes the behavior of always update these JSON definitions. 
It seems that Stackdriver returns the definition of the alerts with the fields in a particular order, so when the `stackdriver.rb` compares the two versions always returns that needs to be updated

GPII-3916 - Change the order in the JSON fields

---

gcp/README.md
gcp/docker-compose.yaml
shared/rakefiles/tests/spec/vars_spec.rb
shared/rakefiles/vars.rb

This PR sets Helm's `HELM_TLS_*` variables to point to correct paths and enables TLS, so that `helm` command works out of the box.

Helm - set ENV variables to make helm work out of the box

---

gcp/README.md
shared/rakefiles/scripts/couchdb_ui.sh

This PR:
- Adds documentation about accessing CouchDB UI and using port-forwarding
- Makes `ui` user password immutable for the lifetime of the given cluster (this is based on cluster's master IP, the user is still deleted when forwarding is stopped).
**TL;DR**: This change should make it more comfortable to use `couchdb_ui` port-forwarding feature.
I've implemented this based on Javi's feedback and discovery that some browsers don't accept user credentials in URL (`user:password`) anymore (Firefox generally works, Chrome is complicated - older versions work, newer ones will accept credentials once and cache these & ask for manual input should these change, Safari will always ask...). There's even RFC suggesting this form as deprecated - https://www.ietf.org/rfc/rfc3986.txt. Making the …

GPII-4023: CouchDB UI access - add docs and make ui user password immutable

---

common/modules/gcp-stackdriver-monitoring/resources/alert_policies/backup_exporter_snapshots_prd.json
common/modules/gcp-stackdriver-monitoring/resources/alert_policies/backup_exporter_snapshots_stg.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/backup_exporter_errors.json
gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/backup_exporter_snapshots.json

Second attempt to fix the "always update" issue when the monitoring is deployed in stg and prd. This time I've saved the JSON definition directly from Stackdriver.
`rake deploy_module["k8s/stackdriver/monitoring"]` output:
```
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "Pod `couchdb-prometheus-exporter` exports a metric" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "IAM audit logs do not contain policy modification events" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "Snapshots are being created for persistent volumes of CouchDB stateful set" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "Stackdriver audit log does not contain alert policy …
```

GPII-3916 - Fix Backup exporter alert definitions

---

common/modules/gcp-project/main.tf

This binding is created by default when Web Security Scanner API is enabled, seems to solve `One of the starting URLs is not hosted on the current project` problem.

[GPII-3902]: Add missing websecurityscanner.serviceAgent binding to gcp-project

---

.circleci/config.yml
common/docker-compose.yaml
gcp/docker-compose.yaml
gcp/modules/gpii-flowmanager/dns.tf

This PR fixes [GPII-4040](https://issues.gpii.net/browse/GPII-4040), error when running `destroy` on a non-existing cluster.
Changes introduced:
- Defer data source `kubernetes_service.istio-ingressgateway` refresh to apply phase
- Bump `exekube` to 0.9.2-google_gpii.0 - includes change to make `tiller_status` fail faster (see https://github.com/gpii-ops/exekube/pull/65 for details)
This PR depends on https://github.com/gpii-ops/exekube/pull/65.
Note: Circle CI tests will fail untill the `0.9.2` `exekube` image is created

Fix error with `data.kubernetes_service.istio-ingressgateway` on destroy

---

common/modules/gcp-external-backup/main.tf
common/modules/gcp-project/main.tf

This PR fixes two issues in the common-stg of the testing organization:
1. The project owner SA needs permissions to modify the Stackdriver and logging services
2. There is a data resource that reads other projects that is not needed and gives a PERMISSION_DENIED.

GPII-3917 Fix testing org common-stg permissions

---

common/modules/gcp-project/main.tf
gcp/live/prd/k8s/kube-system/backup-exporter/terraform.tfvars
gcp/live/stg/k8s/kube-system/backup-exporter/terraform.tfvars
gcp/modules/backup-exporter/main.tf
shared/charts/backup-exporter/templates/configmap.yaml

Changes of this repository:
1. Some path of the buckets were not properly set because the first check of the script fails.
1. Some roles were missing for the SA that is used to access the destination buckets.  The first time that CloudBuild runs tries to set all the permissions by itself. Of course, this is not possible in our environment because the SA that it uses is very limited. So we are setting the permissions instead.
1. STG and PRD don't have the default network that we have in DEV, so the command has been modified to use a particular region, just to store the images before they are sent to the destination bucket.
1. When we change the region, the working bucket used by the Daisy scripts changes.

GPII-3917 Fix issues on deployment

---

shared/rakefiles/stackdriver.rb

Ruby protobuf library removed `to_hash` methods (see details https://github.com/protocolbuffers/protobuf/pull/6166) which breaks our Stackdriver code. This PR fixes the issue.
Changes:
- Use `to_h` instead of removed `to_hash` method
The error below happens on the current fresh build of `exekube` image (although is not present in the `gpii/exekube:0.9.2-google_gpii.0` tag):
```
/rakefiles/stackdriver.rb:111:in `method_missing': undefined method `to_hash' for #<Google::Monitoring::V3::NotificationChannel:0x000056471d319420> 
```
_Note: Looks like our `exekube` builds are a bit behind, so quite a few libraries got updated when rebuilding from scratch, probably caused by combination of caching and use of `alpine:3.8`:_
```
google-cloud-env (1.0.5)                            | …
```

GPII-4057: Fix use of removed to_hash in custom Stackdriver code

---

gcp/README.md

At the end, I decided that it was worth keeping the instructions for generating db data for users, just in case it's needed in the future so I reworked the section a bit.

GPII-4045: Added instructions for loading credentials into CouchDB

---

ONE-TIME-SETUP.md

Document deletion of default org-wide permissions in one-time setup doc.

Document deletion of default GCP permissions

---

.circleci/config.yml
common/docker-compose.yaml
common/modules/gcp-project/main.tf
gcp/docker-compose.yaml
gcp/modules/gke-network/main.tf
shared/rakefiles/scripts/clean_fw_rules.sh

This PR addresses [GPII-4061 - Review & clean up GCP firewall rules](https://issues.gpii.net/browse/GPII-4061).
- Remove duplicate firewall rules created by exekube (see https://github.com/gpii-ops/exekube/pull/66 for details)
- Move default network deletion to native TF
- Manual cleanup of orphaned FW rules and default networks (see deployment plan)
This PR depends on https://github.com/gpii-ops/exekube/pull/66
_Note: Circle CI should pass once https://github.com/gpii-ops/exekube/pull/66 is merged and tag created._
**Deployment plan:**
```
gcloud compute networks delete default --project gpii2test-common-stg
gcloud compute networks delete default --project gpii-common-prd
```
```
gcloud compute networks delete forseti --project gpii2test-common-stg
```
FW rules …

GPII-4061: Clean up fw rules

---

gcp/live/dev/k8s/gpii/couchdb/terraform.tfvars
gcp/live/prd/k8s/gpii/couchdb/terraform.tfvars
gcp/live/stg/k8s/gpii/couchdb/terraform.tfvars
gcp/modules/couchdb/main.tf

To have consistency with stg and prd clusters.
We have enough room for one more replica, no need to change workers flavor (we actually have more than needed – after upgrade around 4CPUs and 4GB of RAM is still allocatable across all nodes).
I also verified some scenarios (CouchDB upgrade, K8s upgrade, preferences / flowmanager rollouts) and did not find any unwanted side effects.

[GPII-4068]: Bump CouchDB replica_count to 3 in dev

---

.gitlab-ci.yml

This is small regression, introduced in https://github.com/gpii-ops/exekube/pull/67

Fix gcp-unit-tests

---

.circleci/config.yml
common/docker-compose.yaml
common/modules/gcp-stackdriver-lbm/main.tf
common/modules/gcp-stackdriver-monitoring/main.tf
gcp/docker-compose.yaml
gcp/modules/gcp-stackdriver-lbm/main.tf
gcp/modules/gcp-stackdriver-monitoring/main.tf
shared/rakefiles/tests/Gemfile
shared/rakefiles/tests/Gemfile.lock

Reverts gpii-ops/gpii-infra#475
After couple unsuccessful attempts to fix GitLab's unit tests:
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/271000726
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/271079217
I will address this in more organized way at better time.

Revert "[GPII-4057]: Use bundler with Stackdriver"

---

gcp/live/dev/k8s/gpii/flushtokens/terraform.tfvars
gcp/live/prd/k8s/gpii/flushtokens/terraform.tfvars
gcp/live/stg/k8s/gpii/flushtokens/terraform.tfvars
gcp/modules/gpii-flushtokens/main.tf
gcp/modules/gpii-flushtokens/values.yaml
shared/charts/gpii-flushtokens/Chart.yaml
shared/charts/gpii-flushtokens/README.md
shared/charts/gpii-flushtokens/templates/NOTES.txt
shared/charts/gpii-flushtokens/templates/_helper.tpl
shared/charts/gpii-flushtokens/templates/cronjob.yaml
shared/charts/gpii-flushtokens/values.yaml
shared/versions.yml

**NOTE**: As of 09-Aug-2019, this pull request references a tagged version of the [gpii-universal docker image](https://ci.gpii.net/job/docker-gpii-universal-master-calculate-tag/33/console):
```
repository: gpii/universal
tag: 20190809170605-f8485e9
```
**NOTE**:  There should be an associated pull request for `gpii-version-updater`, but as of 09-Aug-2019, when attempting to create one, github says there are no differences with respect to the master branch and my GPII-3888 branch.  For now, the associated pull request is [PR #22](https://github.com/gpii-ops/gpii-version-updater/pull/22), which has already been merged into master.
JIRA: https://issues.gpii.net/browse/GPII-3888
<del>
**NOTE**: As of 09-Aug-2019, this pull request references @cindyli's development version of the docker …

GPII-3888: Periodic task to remove expired access tokens from the production Couch database

---

gcp/README.md

This PR adds a note about using `couchdb_ui` credentials to execute ad hoc commands against the database and an example of probably the simplest way to do so from within a docker container.
(Should you want to run queries from within the cluster, e.g. using `kubectl run`, you can still use the credentials but you'll need to find out and use DNS specific for one pod, e.g. `couchdb-couchdb-0.couchdb-couchdb.gpii.svc.cluster.local`. I left this out as I believe the documented way is easier).

Add note about using couchdb_ui credentials to run scripts

---

shared/charts/gpii-flowmanager/templates/deployment.yaml
shared/charts/gpii-preferences/templates/deployment.yaml

I've missed to include this change in https://github.com/gpii-ops/gpii-infra/pull/485. Some of the network policies won't work without it.

GPII-2865: Add names to ports for Preferences and Flowmanager

---

gcp/modules/gpii-istio/network_policy.tf

This PR is the second part of implementing Network Policies for services in GPII namespace - [GPII-2865](https://issues.gpii.net/browse/GPII-2865).
This PR implements default "deny" and should only be merged after #485.
This PR:
- Adds default deny Ingress Network Policy for GPII namespace
Deploy plan:
- Verify that deny policy is in effect by starting an interactive container `kubectl run -it --restart=Never --image=gcr.io/gpii-common-prd/gpii__locust:0.9.0-gpii.6 test -n gpii -- /bin/sh` and running following commands:
```console
$ curl -k -s -w "%{http_code}" -o /dev/null http://preferences.gpii.svc.cluster.local/health
503~ $
$ curl -k -s -w "%{http_code}" -o /dev/null http://flowmanager.gpii.svc.cluster.local/health
503~ $
$ curl -k -s -w "%{http_code}" -o /dev/null …
```

GPII-2865: Implement Network policies - pt. 2

---

gcp/modules/gpii-istio/network_policy.tf

Second try to implement default deny Network Policy for services in GPII namespace - [GPII-2865](https://issues.gpii.net/browse/GPII-2865).
While Terraform Kubernetes provider [documentation](https://www.terraform.io/docs/providers/kubernetes/r/network_policy.html) says:
> ingress - (Optional) List of ingress rules ....... **If this field is empty then this NetworkPolicy does not allow any traffic** (and serves solely to ensure that the pods it selects are isolated by default).
it in fact results in policy allowing all traffic. To get policy denying all traffic, this field has to be omitted.
*Note: I intend to follow up with PR against Terraform provider to improve the documentation, will be linked.*
This PR:
- Fixes default deny Ingress Network Policy for GPII namespace to actually block …

GPII-2865: Fix default deny network policy

---

gcp/modules/istio/tracing.tf

This fix addresses the race condition when Istio tracing rule takes a while on cluster creation.
```
null_resource.istio_tracing: Error running command 'kubectl patch -n istio-system --request-timeout 5s rule stackdriver-tracing-rule -p '{"spec":{"match":"context.protocol == \"http\" || context.protocol == \"grpc\""}}' --type merge': exit status 1. Output: Error from server (NotFound): rules.config.istio.io "stackdriver-tracing-rule" not found
```

GPII-4085: Fix race condition for Istio tracing rule

---

.circleci/config.yml
.gitlab-ci.yml
common/docker-compose.yaml
gcp/docker-compose.yaml
gcp/modules/istio/hpa.tf

This PR is part of [GPII-4085](https://issues.gpii.net/browse/GPII-4085).
This PR:
- Bumps exekube image version, this image adds new Istio GKE GCR registry to whitelist, see https://github.com/gpii-ops/exekube/pull/68 for details
- Aligns tags for HPAs to ones used by GKE post 1.1 upgrade
This PR depends on https://github.com/gpii-ops/exekube/pull/68.

GPII-4085: Add new Istio GCR registry to whitelist

---

.circleci/config.yml
.gitlab-ci.yml
common/docker-compose.yaml
gcp/docker-compose.yaml

This PR fixes [GPII-4110](https://issues.gpii.net/browse/GPII-4110).
This PR:
- Bumps exekube image version, this image adds new Istio GKE GCR registry to whitelist, see https://github.com/gpii-ops/exekube/pull/69 for details
This PR depends on https://github.com/gpii-ops/exekube/pull/69.
The https://github.com/gpii-ops/exekube/pull/69 also has to be merged for the CircleCI checks to work.

GPII-4110: Bump exekube version to 0.9.6

---

shared/rakefiles/scripts/quarantine_node.sh

The basic functions are automated, but I left the "interface" pretty raw as I'm not sure how we want to implement it:
1. (current implementation) Manually comment/un-comment parts you want to run
* Not very elegant, but it's hard to anticipate what the workflow might look like during a real incident. A manual solution is very flexible without a lot of effort for a script that will be exercised rarely.
2. Add support for subcommands
* This could be one subcommand per function:
```
quarantine_node.sh create_firewall_rules
quarantine_node.sh remove_node_from_instance_group
...
quarantine_node.sh delete_firewall_rules
```
* Or it could be less granular with only a few "special" steps isolated:
```
quarantine_node.sh quarantine
quarantine_node.sh destroy
```
3. One function (or a couple …

GPII-2806: Add script for quarantining nodes during a Security Incident.

---

gcp/modules/locust/tasks/flowmanager.py
gcp/modules/locust/tasks/preferences.py

This PR adds additional debug output to locust workers in case of errors. Related to work on debugging 404 errors [GPII-4111](https://issues.gpii.net/browse/GPII-4111).
At the moment it's very difficult do debug errors with limited output Locust provides - for example Locust does not show headers for failed requests (without headers it's difficult to determine whether the failure is coming from Envoy).
This PR adds additional output to locust workers in case of failures.
Example of output added to worker logs:
```yaml
Request: GET /preferences/omar
URL: http://preferences.gpii.svc.cluster.local/preferences/omar
Exception: 503 Server Error: Service Unavailable for url: http://preferences.gpii.svc.cluster.loca
Code: 503
Headers: {'content-length': '91', 'content-type': 'text/plain', 'date': …
```

GPII-4111: Add additional locust output on failure

---

shared/charts/couchdb/Chart.yaml
shared/charts/couchdb/templates/destination_rule.yaml
shared/charts/gpii-flowmanager/Chart.yaml
shared/charts/gpii-flowmanager/templates/destination_rule.yaml
shared/charts/gpii-preferences/Chart.yaml
shared/charts/gpii-preferences/templates/destination_rule.yaml

This PR fixes [GPII-4111](https://issues.gpii.net/browse/GPII-4111) - low number of 404s we recently observed in our pipeline.
Roughly 0.02% of requests to database would fail in 503 error, which further results in 404 error returned by preferences. Based on my investigation this happens only in case of `istio-proxy` to `istio-proxy` traffic, and is related to connection pooling (Istio reuses connections for multiple requests). Istio-proxy on the client side will try to send traffic over a connection that has already been closed, and this results in 503 error `upstream connect error or disconnect/reset before headers. reset reason: connection termination`.
See https://gist.github.com/stepanstipl/51780eb0755ec9d177b6da9df5baaa61 for more details.
This seems to be caused by known issue in …

GPII-4111: Fix 404 failures

---

common/modules/gcp-project/main.tf

This should fix CI error with Binary Auth API being disabled - [GPII-4141](https://issues.gpii.net/browse/GPII-4141):
```
* google_binary_authorization_policy.policy: Error creating Policy: googleapi: Error 403: Binary Authorization API has not been used in project 224490750817 before or it is disabled. Enable it by visiting https://console.cloud.google.com/apis/api/binaryauthorization.googleapis.com/overview?project=224490750817 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```
Seems like Binary Authorization now requires `bigquery.googleapis.com` API to be enabled.
I found out about this based on CI run - https://gitlab.com/gpii-ops/gpii-infra/-/jobs/303619443 - and following `gcloud` message when trying to disable …

GPII-4141: Fix disabled BinAuth API error

---

common/modules/gcp-project/main.tf

Looks like we need `bigquerystorage.googleapis.com` too:
```
The service bigquerystorage.googleapis.com is depended on by the following active services: binaryauthorization.googleapis.com,resourceviews.googleapis.com,replicapoolupdater.googleapis.com,container.googleapis.com,bigquery-json.googleapis.com,replicapool.googleapis.com
```
This should fix CI error with Binary Auth API being disabled - [GPII-4141](https://issues.gpii.net/browse/GPII-4141):

GPII-4141: Enable bigquerystorage API to fix bin-auth error

---

gcp/modules/couchdb/values.yaml
shared/charts/couchdb/Chart.yaml
shared/charts/couchdb/README.md
shared/charts/couchdb/templates/statefulset.yaml
shared/charts/couchdb/templates/virtual_service.yaml
shared/charts/couchdb/values.yaml

Original PR (https://github.com/gpii-ops/gpii-infra/pull/489) got reverted because of the unrelated issue with Istio connection pooling that is being addressed in https://github.com/gpii-ops/gpii-infra/pull/507.

[GPII-4068]: Improve CouchDB rollouts with lifecycle hooks, second try 

---

gcp/README.md

We have `destroy_hard` task that we use in CI and that destroys not only infra resources but secrets and TF state as well.
This PR adds notes on how to use it into `Tearing down an environment` section.

[GPII-4053]: Add notes about destroy_hard into README

---

shared/rakefiles/secrets.rb
shared/rakefiles/xk_util.rake

This PR improves secret key rotation task to destroy disabled KMS key versions, so Google won't charge us for them.
Destruction operations is irreversible, so it keeps 10 most recent disabled key versions in case we may need them.

[GPII-4090]: Destroy disabled KMS key versions during secrets key rotation

---

common/modules/gcp-project/main.tf

Seems like Google rolled `bigquery.googleapis.com` as the new name for `bigquery-json.googleapis.com`, that’s when we got the first error with BQ/BinAuth (#510, #511, [GPII-4141](https://issues.gpii.net/browse/GPII-4141)), and now, because it was causing a lot of issues, they rolled it back. And that's why we're seeing:
```
1 error occurred:
* google_project_services.project: 1 error occurred:
* google_project_services.project: Error updating services: googleapi: Error 503: The service(s) ["bigquery.googleapis.com"] are still being enabled for project gpii2test-gcp-stg. This isn't a real API error, this is just eventual consistency.
```
This PR removes `bigquery.googleapis.com` and should fix the issue (at least until Google decides to roll it out again or …

GPII-4141: Fix (again) bigquery api still being enabled error

---

gcp/modules/gpii-istio/network_policy.tf

Part of [GPII-4046](https://issues.gpii.net/browse/GPII-4046). Traffic between Istio's Prometheus (`promsd`) and Istio sidecars in GPII is being blocked and it prevents Prometheus from scraping metrics from sidecar containers. It is due to missing network policies.
This PR adds a rule to allow metric scraping traffic from Prometheus (`app: promsd`) to any pod in GPII namespace, on port `9090` (`http-envoy-prom`).

GPII-4046: Allow promsd to Envoy sidecars

---

shared/rakefiles/entrypoint_common.rake
shared/rakefiles/xk_util.rake

This PR:
* Adds `:display_scc_findings` task to display active findings.
* Adds parametrized `:display_scc_assets_changed` task that by default displays added or removed assets for `gpii-gcp-prd`, `gpii-common-prd` using 1 week as comparison duration and excludes noisy assets like KMS keys and Snapshots from the output.
Downsides: SCC commands are in alfa state, so we may probably face similar field naming changes or other issues that we've been recently facing using UI.

[GPII-4151]: Add SCC tasks

---

.circleci/config.yml
.gitlab-ci.yml
common/docker-compose.yaml
gcp/docker-compose.yaml
gcp/live/prd/secret-mgmt/terraform.tfvars
gcp/live/stg/secret-mgmt/terraform.tfvars
gcp/modules/gcp-secret-mgmt/main.tf

This PR enables secrets bucket versioning for staging and production environments and should be merged after https://github.com/gpii-ops/exekube/pull/70.
Deployment does not require any special treatment.

[GPII-3836]: Enable secrets bucket versioning for stg, prd

---

shared/rakefiles/secrets.rb
shared/rakefiles/tests/spec/secrets_spec.rb

This PR adds new functionality to secret management code:
* In case new secrets added into configuration, while encrypted secrets are already present, they'll now be correctly populated and pushed.
* In case some secrets were removed from configuration, while encrypted secrets are already present, they'll be correctly removed from remote encrypted secrets as well.

[GPII-4052]: Secret management improvements

---

gcp/modules/locust/swarm.tf

This PR increases the number of retries when waiting for Locust worker nodes to join master - [GPII-4181](https://issues.gpii.net/browse/GPII-4181).
This is caused by a race condition in Istio, when it doesn't get complete configuration from Pilot. This happens when the container is not ready before `istio-proxy` is. See https://github.com/istio/istio/pull/13228 for details, PR fixing this is https://github.com/istio/istio/pull/13229. Unfortunately, this fix is not present in neither 1.1.13 (current GKE) or soon to be released on GKE 1.1.16 version.
This fix helps because Istio does full config reload after 5 minutes.
**Testing:**
I've tested this in staging and was able to finish more than 20 `test_preferences` runs without seeing the issue (before the fix it would fail every 2nd/3rd …

GPII-4181: Increase wait for Locust workers

---

gcp/live/dev/k8s/kiali/terraform.tfvars
gcp/live/prd/k8s/kiali/terraform.tfvars
gcp/live/stg/k8s/kiali/terraform.tfvars

Looks like I missed dependency on `helm-initializer` and didn't catch this during testing (this creates a race condition between helm-init and Kiali) as part of the work on [GPII-4046](https://issues.gpii.net/browse/GPII-4046).
This PR adds the missing dependency on `helm-initializer`.

GPII-4046: Add missing dependency on helm-initializer

---

shared/rakefiles/xk_util.rake

Recently added `display_scc_*` tasks are missing dependency on `configure`, and will fail when called without authentication previously done by another task.
This PR adds the missing dependency.
**Steps to reproduce:**
- run `rake clobber` do discard temporary volumes
- run `rake display_scc_findings`
The task will fail with auth error:
```console
$ RAKE_REALLY_RUN_IN_PRD=true rake display_scc_findings
docker-compose run --rm xk rake display_scc_findings
Creating volume "gpii-common-prd-stepan-secrets" with default driver
Creating volume "gpii-common-prd-stepan-helm" with default driver
Creating volume "gpii-common-prd-stepan-gcloud" with default driver
Creating volume "gpii-common-prd-stepan-kube" with default driver
gcloud alpha scc findings list 247149361674 --filter 'state = "ACTIVE"' …
```

Add missing configure dependency for SCC tasks

---

gcp/modules/gke-cluster/main.tf

This PR reenables automatic "follow the default version" behavior and effectively upgrades GKE Masters and control plane to `1.13.10-gke.0`. [GPII-4119](https://issues.gpii.net/browse/GPII-4119).
Nodes are not upgraded immediately but will be upgraded in the next maintenance window. I have also tested cluster functionality after triggering the node upgrade manually and everything seems good.
I hoped to upgrade directly to `1.13.11-gke.3` which should contain a fix for [CVE-2019-15226](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-15226) and Istio` 1.1.16`, and was supposed to be released between October 8 and October 12. Unfortunately, it's still not available across all regions.

GPII-4119: Upgrade GKE to 1.13

---

shared/rakefiles/xk_infra.rake

This PR modifies common infra task that enforces org-level permissions to set missing Organization Viewer role for our common support account.
From the [Role-based Support documentation](https://cloud.google.com/support/docs/role-based-support):
`To access support cases for your organization's support account, a user must have the ability to view the organization. This means that Support Account Administrators and all support users must have the Organization Viewer role assigned at the organization level.`

[GPII-4194]: Set missing org-level permissions for common support account

---

shared/charts/k8s-snapshots/README.md
shared/charts/k8s-snapshots/templates/deployment.yaml
shared/versions.yml

This PR switches `k8s-snapshots` to use latest image that is [free from critical vulnerabilities](https://console.cloud.google.com/gcr/images/gpii-gcp-dev-natarajaya/GLOBAL/k8s-snapshots@sha256:5c9a27ae0a37e0d4d0a6cb2d89e6b859af7a01ef9d9864b647fb4927e11c741e/details?tab=vulnz&project=gpii-gcp-dev-natarajaya&authuser=1&organizationId=247149361674), and fixes its chart to work properly with the new version.
I have tested this with my dev cluster and have not found any side effects, but using latest build seems like a bad idea anyway. Initially I wanted to pin it down to specific SHA, but looks like our version-updater [can only work with tags](https://github.com/gpii-ops/gpii-version-updater/blob/master/sync_images.rb#L41-L47) :(
Should we push to our docker registry, add a tag and let …

[GPII-4205]: Upgrade k8s-snapshots to latest

---

gcp/modules/istio-gke-helper/main.tf
shared/charts/istio-gateways/Chart.yaml
shared/charts/istio-gateways/templates/_affinity.tpl
shared/charts/istio-gateways/templates/_helpers.tpl
shared/charts/istio-gateways/templates/_podDisruptionBudget.tpl
shared/charts/istio-gateways/templates/deployment.yaml
shared/charts/istio-gateways/templates/service.yaml
shared/charts/istio-gateways/templates/serviceaccount.yaml
shared/charts/istio-gateways/values.yaml

This PR deploys Istio Egress gateway as part of work on controlling egress traffic - [GPII-4102](https://issues.gpii.net/browse/GPII-4102). Egress gateway used to be deployed as part of the GKE istio add-on by default prior to 1.1 (with all egress traffic blocked).
The PR does not affect the current flow of egress traffic in any way, not blocks any traffic, this will be handled in separate PRs.
**PR Changes:**
- Add Istio gateways chart - the chart is based on official Istio charts, but refactored to work as a standalone chart (vs. original subchart) and with some bits of not relevant functionality removed from templates
- Deploy an instance of Istio Egress gateway
**Deployment:**
This is a non-disruptive deploy.
**Testing:**
I've tested that the Egress gateways is correctly deployed and …

GPII-4102: Add Istio Egress Gateway

---

common/live/stg/infra/stackdriver/monitoring/terraform.tfvars

This PR remove the dependency of LBM module in common-stg and unlocks the pipeline.

[GPII-3965] Remove lbm module dependency on common-stg

---

gcp/modules/gcp-stackdriver-monitoring/notification_alerts_slack.tf

It seems that the `display_name` is translated to the `Channel name` of the alert. After changing this in one alert in stg, new messages appeared in the channel.

[GPII-4220] Alerts not received in Slack

---

.circleci/config.yml
.gitlab-ci.yml
common/docker-compose.yaml
gcp/README.md
gcp/docker-compose.yaml
shared/rakefiles/entrypoint.rake
shared/rakefiles/scripts/couchdb_backup_restore.sh
shared/rakefiles/xk_util.rake

This PR adds a script to automate restore of CouchDB cluster from snapshots ([GPII-4221](https://issues.gpii.net/browse/GPII-4221)).
This PR depends on https://github.com/gpii-ops/exekube/pull/71.
**PR Changes introduced:**
- Add CouchDB Backup restore script.
The script does the following main steps (in-order):
- (optional) Reads latest set of snapshots
- Checks snapshots availability
- Scales down services (flowmanager & preferences)
- Reads CouchDB volume names
- Scales down CouchDB
- Scales down k8s-snapshots
- Deletes and restores individual volumes from snapshots
- Scales up CouchDB
- Checks CouchDB health (both individual nodes and overall cluster membership)
- Scales up services
- Scales up k8s-snapshots
- Add CouchDB Backup restore rake task
- Add documentation for CouchDB …

GPII-4221: Automate CouchDB Backup Restore

---

gcp/modules/gcp-stackdriver-monitoring/alert_k8s_snapshots_couchdb.tf
gcp/modules/gcp-stackdriver-monitoring/alert_k8s_snapshots_errors.tf

This PR disables K8s snapshots alerts till [GPII-4229](https://issues.gpii.net/browse/GPII-4229) is resolved.

GPII-4229: Disable k8s alerts till resolved

---

gcp/modules/gpii-istio/main.tf
gcp/modules/gpii-istio/network_policy.tf

This PR adds network policies to block egress external traffic unless it's going via the egress gateway, it's part of work on controlling egress traffic - [GPII-4102](https://issues.gpii.net/browse/GPII-4102). This will effectively bring us back to the state before GKE Istio 1.1, when any egress traffic was denied by default.
**PR Changes:**
- Block egress traffic from `gpii` namespace - egress traffic is blocked by default, there are several exceptions:
- Egress to Istio control plane is allowed - this is required for traffic routed via Egress gateway and other Istio traffic to istio control plane
- Egress traffic within `gpii` namespace is allowed (traffic is already controlled by ingress rules on corresponding services)
- Egress traffic to Kube DNS service is allowed
- Egress traffic …

GPII-4102: Block egress traffic

---

shared/rakefiles/xk_util.rake

This PR contains fix suggested by Google Support that excludes Google-managed SA keys from assets changed.
Unfortunately, `gcloud` filter does not work properly when I mix SCC attributes and resource properties, so I had to filter them with `jq` instead.

[GPII-4224]: Exclude Google-managed SA keys from :display_scc_assets_changed output

---

gcp/modules/gcp-stackdriver-monitoring/main.tf
gcp/modules/gcp-stackdriver-monitoring/notification_email.tf

This PR use the old code that left behind the alerts upgrade.

[GPII-4238] The mail notification channel of the devs clusters is alerts+dev

---

shared/charts/k8s-snapshots/README.md
shared/charts/k8s-snapshots/templates/deployment.yaml
shared/versions.yml

Team noticed random spikes in amount of snapshots across multiple environments after upgrade.
This PR reverts gpii-ops/gpii-infra#531.

Revert "[GPII-4205]: Upgrade k8s-snapshots to latest"

---

gcp/modules/gcp-stackdriver-monitoring/alert_flowmanager_ssl_cert_check.tf

This PR:
* Contains change that combines multiple conditions into single alert policy that I though was already committed to #548 
* Prevents TF from creating `ssl-cert-check` alert policy for ephemeral envs: Stackdriver is [not happy](https://gitlab.com/gpii-ops/gpii-infra/-/jobs/360834150) when we try to create alert policy based on custom metric that is not yet exists. This fix is needed to unblock the pipeline, I'll work on permanent solution later.

[GPII-3681]: Leftovers and fixes for ephemeral environments

---

shared/versions.yml

This pull reverts the universal container version changed in [the previous deployment pull](https://github.com/gpii-ops/gpii-infra/pull/556).

GPII-4243:  Reverting to previous version of universal container image.

---

shared/versions.yml

My [previous attempt](https://github.com/gpii-ops/gpii-infra/pull/531) to solve `k8s-snapshots` security issues was [not very successful](https://github.com/gpii-ops/gpii-infra/pull/555).
New image is a better solution: https://github.com/gpii-ops/k8s-snapshots/pull/1
In progress, because I need some time to test it in my dev cluster.

[GPII-4205]: Use k8s-snapshots:0.2.1-gpii.0

---

.circleci/config.yml
.gitlab-ci.yml
common/docker-compose.yaml
gcp/docker-compose.yaml

This PR adds missing `gke.grc.io` rule to the Bin-auth whitelisted images patterns and fixes one of the errors observed in [GPII-3850](https://issues.gpii.net/browse/GPII-3850).
```
Failed:
Create pod
kube-proxy-gke-k8s-cluster-terraform-20190319173-571935b8-99sf failed to be created
```
This PR depends on https://github.com/gpii-ops/exekube/pull/72.
**Changes:**
- Bump Exekube version to 0.9.9 - adds `gke.grc.io` to whitelisted registries
**Deployment:**
This is a no-downtime deployment.
**Testing:**
This change has been tested in dev cluster.
_Note: the tests are only expected to pass once the https://github.com/gpii-ops/exekube/pull/72 is merged._

GPII-3850: Use new 0.9.9. exekube image - fix missing bin-auth whitelist

---

gcp/modules/gcp-stackdriver-monitoring/alert_couchdb_prometheus_exporter_exports_metric.tf
gcp/modules/gcp-stackdriver-monitoring/alert_flowmanager_uptime.tf

Increase the time to wait for condition only in ephemeral clusters for the alerts:
- Pod `couchdb-prometheus-exporter` exports a metric 
- Uptime check on `flowmanager.alfredo.dev.gcp.gpii.net` is green

[GPII-3241] Reduce alert noise

---

gcp/README.md

[Rendered README](https://github.com/natarajaya/gpii-infra/blob/7c3071ebd6795610afeee0bd4f58ce1026e94856/gcp/README.md#internal-error-occurred-failed-calling-webhook-sidecar-injectoristioio-x509-certificate-signed-by-unknown-authority).

Add note regarding Istio's sidecar injector issues

---

.circleci/config.yml
.gitlab-ci.yml
common/docker-compose.yaml
gcp/docker-compose.yaml

This PR adds missing `gke.grc.io/istio/prometheus/*` rule to the Bin-auth whitelisted images and
fixes the additional error observed in [GPII-3850](https://issues.gpii.net/browse/GPII-3850).
```
pods "promsd-76f8d4cff8-6jmsv" is forbidden: image policy webhook backend denied one or more images: Denied by default admission rule. Overridden by evaluation mode. Denied by default admission rule. Overridden by evaluation mode
```
This PR depends on https://github.com/gpii-ops/exekube/pull/73.
**Changes:**
- Bump Exekube version to 0.9.10 - adds `gke.grc.io/istio/prometheus/*` to whitelisted registries
**Deployment:**
This is a no-downtime deployment.
**Testing:**
This change has been tested in the dev cluster.
_Note: the tests are only expected to pass once the …

GPII-3850: Use new 0.9.10 exekube image - fix additional missing bin-auth rule

---

common/modules/gcp-project/main.tf

This PR fixes error observed in CI:
```
1386 1 error occurred:
1387 	* google_project_services.project: 1 error occurred:
1388 	* google_project_services.project: Error updating services: googleapi: Error 503: The service(s) ["bigquery-json.googleapis.com"] are still being enabled for project gpii2test-gcp-prd. This isn't a real API error, this is just eventual consistency.
```
This issue is caused By Google's rename of `bigquery-json.googleapis.com` to `bigquery.googleapis.com`  - see https://cloud.google.com/bigquery/docs/release-notes#October_23_2019 for details.

GPII-4280: Fix bigquery api error

---

gcp/modules/gcp-stackdriver-export/gpii_key.tf

This PR adds BigQuery dataset and configures Stackdriver logging sink to export preferences and flowmanager container logs containing GPII keys. Entire thing is temporary and only needed so I can collect and analyze data regarding individual key usage.
Exekube's `gcp-stackdriver-export` module does not support BigQuery exports – I tried to fix this, but now abandoned this idea, because supporting both GS and BigQuery sinks requires module refactoring that probably does not worth the effort atm.

[GPII-4158]: Export preferences and flowmanager logs containing GPII keys to BigQuery

---

common/modules/gcp-project/main.tf

Discrepancy between dev workflow and CI with everything related to common part is a bit annoying...

[GPII-4158]: Add missing permission to projectowner SA

---

common/modules/gcp-project/main.tf
gcp/modules/gcp-stackdriver-export/gpii_key.tf

This PR fixes a conflict between authoritative `google_project_iam_policy` of the common code and unique writer IAM member of the Stackdriver BigQuery logging sink.
I haven't found a way to resolve this conflict without introducing unnecessary cohesion between common code and GCP part, but considering temporary nature of the these resources, I think we can sacrifice `unique_writer_identity` of the sink and grant required permissions to Stackdriver Logging agent instead.

[GPII-4158]: Fix conflicting IAM entities

---

gcp/modules/gke-cluster/main.tf

This PR upgrades GKE clusters to `1.13.11-gke.15`. This version includes Istio `1.1.17` which fixes known security issues, see https://istio.io/news/security/istio-security-2019-007/ for details. ([GPII-3850](https://issues.gpii.net/browse/GPII-3850)).
The fixed GKE version should be removed, once the `1.13.11-gke.15` or newer becomes default (comment added in the code).
**Changes:**
- Bump GKE to fixed version to `1.13.11-gke.15` -  includes Istio `1.1.17`
**Deployment:**
This is a no-downtime deployment.
**Testing:**
This change has been tested in dev cluster.

GPII-4270: Upgrade to 1.13.11-gke.15 - fixes Istio CVEs

---

common/modules/gcp-dns/main.tf
common/modules/gcp-project/main.tf

This PR adds record sets to override all NS records created by `google_dns_managed_zone` primitives to set the proper TTL (3600) instead of default one (21600).
It is impossible to set TTL for the records created by `google_dns_managed_zone`:
https://github.com/terraform-providers/terraform-provider-google/issues/5280
However, as it turns out, TF does not care about DNS records, created by `google_dns_managed_zone`  – as long as the zone entity is unchanged, other records can be modified without causing a conflict.
I tested this running common part only for my project – deployment should be seamless.

[GPII-4211]: Override NS records created by google_dns_managed_zone to set proper TTL

---

.circleci/config.yml
.gitlab-ci.yml
common/docker-compose.yaml
gcp/docker-compose.yaml

This PR updates the exekube version which includes the latest providers available for Terraform 0.11.
This PR depends on https://github.com/gpii-ops/exekube/pull/74

GPII-3718: Set new exekube version

---

shared/versions.yml

This PR adds exekube to versions file, so version-updater can upload it to GCR, where it will be scanned for vulnerabilities.
I tried to fix exekube version checker script to work properly with version-updater image format, but it turns out that find is pretty bad with multiline regex, hence the workaround with the comment.

[GPII-3946]: Add exekube image to version-updater config

---

shared/versions.yml

See [GPII-4262](https://issues.gpii.net/browse/GPII-4262) for more details, including verification procedures.
My idea is that this would be deployed on Monday, December 16th, 2019.  I will comment with performance tests and QA results shortly.

GPII-4262: Deploy revised validation endpoints.

---

gcp/modules/couchdb/main.tf

Hot fix to solve this issue:
```
Error: Error running plan: 1 error occurred:
* provider.google: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/410504806

GPII-3718: add credentials to Google provider

---

.circleci/config.yml
.gitlab-ci.yml
common/docker-compose.yaml
gcp/docker-compose.yaml
shared/rakefiles/scripts/check_exekube_versions.sh

This PR updates all components in the project to use exekube image from GCR and fixes exekube version checker script.

[GPII-3946]: Use exekube from GCR registry

---

shared/versions.yml

This PR upgrades `certmerge-operator` image.
Depends on https://github.com/gpii-ops/docker-image-certmerge-operator/pull/2.
- There are no functional changes introduced in this PR, the `certmerge-operator` itself and image have been updated, see details in https://github.com/gpii-ops/docker-image-certmerge-operator/pull/2 and https://github.com/gpii-ops/certmerge-operator/pull/1.
**Testing:**
The change has been tested in a dev environment.

GPII-4282: Upgrade certmerge-operator image

---

.gitignore
.gitlab-ci.yml
gcp/modules/couchdb/main.tf
gcp/modules/couchdb/morphic_credentials.json
gcp/modules/couchdb/secrets.yaml
gcp/modules/locust/main.tf
gcp/modules/locust/tasks/common.py
gcp/modules/locust/tasks/flowmanager.py
gcp/modules/locust/tasks/morphic_read.py
gcp/modules/locust/tasks/morphic_write.py
gcp/modules/locust/tasks/on_failure.py
gcp/modules/locust/tasks/preferences_read.py
gcp/modules/locust/tasks/preferences_write.py
gcp/modules/locust/values.yaml
shared/charts/locust/Chart.yaml
shared/charts/locust/templates/_helpers.tpl
shared/charts/locust/templates/secrets.yaml
shared/charts/locust/templates/worker-deploy.yaml
shared/charts/locust/values.yaml
shared/rakefiles/ci.rake
shared/rakefiles/entrypoint.rake
shared/rakefiles/secrets.rb
shared/rakefiles/test.rake
shared/rakefiles/tests/spec/secrets_spec.rb

This PR:
* Adds new locust configs to simulate default morphic behaviors.
* Adds functionality to generate uuids to secrets module.
* Fixes secrets rspecs.
* Adds functionality to generate and load morphic credentials for locust to couchdb module.
* Patches locust chart to set morphic env variables for worker deployment.
* Updates CI configs to include new load tests.
After some consideration I decided to not worry about post-test cleanup for now: generated access tokens will expire and got collected by flush tokens job, and few extra thousands prefsets will be reused by locust and it is fine to leave them in DB for static environments.
I tested entire CI workflow in my dev cluster, and have not found any issues.

[GPII-4159] Add locust configs simulating default morphic behaviors

---

TESTING.md
gcp/README.md

See [https://issues.gpii.net/browse/GPII-4272](https://issues.gpii.net/browse/GPII-4272) for details.
IMO this should be reviewed and merged after [Joseph's pull to add the ability to more easialy run the production tests](https://github.com/gpii-ops/gpii-infra/pull/347)

GPII-4272: Update instructions for deploying and performing QA on a new universal container.

---

gcp/modules/certmerge-operator-crd/values.yaml
shared/charts/certmerge-operator-crd/Chart.yaml
shared/charts/certmerge-operator-crd/templates/cert_merge-secretlist.yaml
shared/charts/certmerge-operator-crd/values.yaml
shared/charts/certmerge-operator/Chart.yaml
shared/charts/certmerge-operator/templates/crd.yaml
shared/charts/certmerge-operator/templates/role.yaml
shared/versions.yml

This PR adds mechanism to notify Istio Ingress Gateway when  TLS certificates are updated.
- Update certmerge-operator to v0.0.3-gpii.2
- Update certmerge-operator Chart - CRD and role permissions
- Update certmerge-operator-crd Chart - add support for notify
- Add notification for istio-ingress-gateway
**Downtime:**
This is a no-downtime change and is not expected to have any impact on services.
**Testing:**
Done in dev env - both upgrade of existing and spinning up a new one.

GPII-4282: Propagate TLS cert update

---

shared/charts/backup-exporter/templates/configmap.yaml

[GPII-4187](https://issues.gpii.net/browse/GPII-4187)
The backup exporter script will clean up old resources on every successful backup.

[GPII-4187] Backup-exporter sometimes leaves leftovers in the projects

---

gcp/modules/gke-cluster/main.tf

This PR lifts the version check to resolve error while GKE is being upgraded to new minor across zones. It won't have any other effect as the version is currently locked at `kubernetes_version = "1.13.11-gke.15"`.

GPII-4349: Lift version check while GKE is being upgraded to new minor

---

gcp/modules/gke-cluster/main.tf

Original 1.13.11 is not available in all regions anymore, this is temporary till 1.14 is rolled out as default across all regions.

GPII-4349: Bump version to one available in all regions - 1.13.12-gke.25

---

shared/rakefiles/xk_util.rake

Bumped into this small issue while dealing with locust credentials rotation for stg and prd.

Fix :rotate_secret task to allow use of provided value

---

shared/rakefiles/test.rake

This PR relaxes median / max response time thresholds for all load tests.
There is often a single outlier that causes pipeline failure. I was hesitating to maybe use 95th or 99th percentile as a threshold instead, but ended up just increasing max response time. Since we review Locust stats in Stackdriver anyway, I think this is safe.

[GPII-4159]: Relax locust thresholds

---

gcp/modules/late-alerts/alert_container_restart_rate.tf

This PR improves existing alert on container restart rate, which would actually almost never trigger (there's very little chance that there will be 3 restarts even if the container is in the `CrashLoopBackOff`f state due to exponential back-off starting at 10s).
After going through the past monitoring data, alerting on 3+ restarts over 5m seems reasonable. It will catch containers in `CrashLoopBackOf` and still should not alert if there are 1-2 restarts because of node upgrade.
- Improve container restart alert
**Downtime:**
This is a no-downtime change.
**Testing:**
Testing was done in dev cluster, alert catches failing container.

GPII-4302: Imrove container restart alert

---

gcp/live/dev/k8s/kube-system/kube-state-metrics/terraform.tfvars
gcp/live/prd/k8s/kube-system/kube-state-metrics/terraform.tfvars
gcp/live/stg/k8s/kube-system/kube-state-metrics/terraform.tfvars
gcp/modules/kube-state-metrics/main.tf
gcp/modules/kube-state-metrics/values.yaml
shared/charts/kube-state-metrics/.helmignore
shared/charts/kube-state-metrics/Chart.yaml
shared/charts/kube-state-metrics/README.md
shared/charts/kube-state-metrics/templates/_helpers.tpl
shared/charts/kube-state-metrics/templates/deployment.yaml
shared/charts/kube-state-metrics/templates/role.yaml
shared/charts/kube-state-metrics/templates/role_binding.yaml
shared/charts/kube-state-metrics/templates/service_account.yaml
shared/charts/kube-state-metrics/values.yaml
shared/versions.yml

This PR deploys **kube state metrics** add-on to the clusters. This add-on expores additional Kubernetes cluster-level metrics to Stacdriver. Example of these metrics can be `kube_deployment_spec_replicas` or `kube_pod_status_ready`.
**Changelog:**
- Add kube-state-metrics chart
- Add kube-state-metrics TF module
- Deploy kube-state-metrics module across environments
- Update prometheus-to-sd-exporter to v0.9.2
- Add kube-state-metrics docker image to versions
**Testing:**
These changes have been tested in dev env, both updating existing and creating new cluster from scratch.
**Downtime:**
This is a no-downtime change, no impact on services is expected.
**_~Note: This is WIP~_**
There is couple of error messages from the prometheus-to-sd I want to look at prior to merging:
```
E0312 …
```

Deploy kube state metrics

---

shared/charts/kube-state-metrics/values.yaml

Seems like Stackdriver metrics are expensive, reduce number of collected metrics only to those we plan to use.
**Changelog:**
- Reduce number of collected metrics by kube-state-metrics (GPII-4414).
**Testing:**
These changes have been tested in dev env.
**Downtime:**
This is a no-downtime change, no impact on services is expected.

GPII-4414: Reduce number of collected metrics

---

gcp/live/dev/k8s/stackdriver-gke/terraform.tfvars
gcp/live/prd/k8s/stackdriver-gke/terraform.tfvars
gcp/live/stg/k8s/stackdriver-gke/terraform.tfvars
gcp/modules/gke-cluster/stackdriver-sync.tf
gcp/modules/stackdriver-gke/main.tf
shared/charts/kube-state-metrics/Chart.yaml
shared/rakefiles/scripts/sync_gke_stackdriver_state.sh

Stackdriver metadata agent suffers from a known issue of being OOM killed - https://stackoverflow.com/questions/60541105/stackdriver-metadata-agent-cluster-level-gets-oomkilled
This PR fixes the issue by increasing allocated resources by modifying the `stackdriver-metadata-agent` ConfigMap.
- Add Stackdriver state sync shell script
- Add Stackdriver sync script trigger to `gke-cluster` module
- Add `stackdrver-gke` TF module - this manages the `stackdriver-metadata-agent` ConfigMap
- Deploy `stackdriver-gke` module in all envs
**Testing:**
**Downtime:**
None expected, this is a zero-downtime change. Stackdriver metadata agent is already broken.

GPII-4426: Fix StackDriver metadata agent

---

shared/charts/kube-state-metrics/Chart.yaml

The change from https://github.com/gpii-ops/gpii-infra/pull/602 was not applied correctly, as the Terraform/Helm does not recognize when only default values change.
This should fix the issue and apply the change by increasing Helm chart version.

GPII-4414: Bump kube-state-metrics chart version to trigger update

---

gcp/modules/stackdriver-gke/main.tf

After fixing the Stackdriver metadata agent, so that is is is actually running, it started triggering CPU alerts.
This PR fixes the issue by increasing allocated resources by modifying the `stackdriver-metadata-agent` ConfigMap.
- Fix StackDriver metadata agent running out of CPU
**Testing:**
**Downtime:**
None expected, this is a zero-downtime change. Stackdriver metadata agent is already broken.

GPII-4434: Fix StackDriver metadata agent running out of CPU

---

shared/versions.yml

This pull updates universal to fix the issues when saving the color vision settings. There is no data migration needed.
See GPII-4438 for more details.

GPII-4438: Updated to universal container that fixes color vision

---

shared/rakefiles/entrypoint_common.rake
shared/rakefiles/xk_util.rake

This PR adds `display_image_vulnerabilities` rake task to display container image vulnerabilities for images is the GCR registry.
Sample output:
```json
$ RAKE_REALLY_RUN_IN_PRD=true rake display_image_vulnerabilities
...
...
{
"image": "https://gcr.io/gpii-common-prd/couchdb@sha256:26a1962d06a5e5be965e517c69d2452c82edf335208ed51360d3493724591e2c",
"vuln_counts": {
"CRITICAL": 2,
"HIGH": 18,
"LOW": 18,
"MEDIUM": 87
}
}
{
"image": "https://gcr.io/gpii-common-prd/couchdb@sha256:b877af600e293895f04c59e49e685dee7fa7aaf4bcfafb516491ebd1d9152543",
"vuln_counts": {
"CRITICAL": 2,
```
- Add display_image_vulnerabilities rake task
**Testing:**
Tested in common PRD environment and local dev.
**Downtime:**
None expected, this is a zero-downtime change.

(GPII-4431) Add display_image_vulnerabilities rake task

---

shared/charts/istio-gke-helper/Chart.yaml
shared/charts/istio-gke-helper/templates/destination_rule.yaml
shared/charts/istio-gke-helper/templates/gateway.yaml
shared/charts/istio-gke-helper/templates/virtual_service.yaml

Egress TLS config is different for Istio 1.2.x. This PR fixes broken TLS  passthrough traffic.
- Fix egress TLS traffic - move to Istio PASSTHROUGH config possible with 1.2.x+
**Testing:**
Tested in local dev.
**Downtime:**
None expected, this is a zero-downtime change.

GPII-4466: Fix egress TLS traffic

---

gcp/modules/couchdb/main.tf
gcp/modules/couchdb/values.yaml
shared/charts/couchdb/Chart.yaml
shared/charts/couchdb/templates/statefulset.yaml
shared/charts/couchdb/values.yaml

This PR moves the CouchDB chart to use SHAs instead of tags, to enforce consistent versions of images used by CouchDB. CouchDB images fairly often get updated, while keeping the same tag and currently this results in inconsistent images across our environments.
- CouchDB chart: Add support for shas
- CouchDB module: switch to using SHAs
**Testing:**
Tested in local dev.
**Downtime:**

GPII-4471: Update CouchDB chart to use SHAs

---

shared/charts/couchdb/templates/statefulset.yaml

This fixes an issue that prevented new cluster creation after moving CouchDB Chart to SHAs - #614 .
- CouchDB chart - fix StatefulSet manifest for assembler
**Downtime:**

CouchDB - fix StatefulSet manifest for assembler

---

shared/rakefiles/scripts/couchdb_backup_restore.sh

This PR adds some additional safety checks to prevent CouchDB restore running in things are not as expected, mainly if:
- CouchDB StatefulSet is scaled to 0
- If a retrieved number of PVs does not match number of replicas

Couch restore check non zero

---

gcp/modules/late-alerts/alert_workloads.tf

This PR fixes alert modification issue on every run. Terraform doesn't handle this quite correctly, on that note the Monitoring API behaves differently to other GCP APIs where the payload would typically be present with a default value.
- Fix alert modification alert
**Downtime:**
**Testing:**

GPII-4476: Fix alert modification alert

---

common/modules/gcp-project/main.tf
gcp/live/dev/k8s/late-alerts/terraform.tfvars
gcp/live/prd/k8s/late-alerts/terraform.tfvars
gcp/live/stg/k8s/late-alerts/terraform.tfvars

This PR fixes **stackdriver-metadata-agent-cluster-level**, component that was crashin because insufficient permissions to submit metrics to Stackdriver, and also aims to eliminate some sales for ephemeral environments by introducing dependency.
- Add stackdriver.resourceMetadata.writer role to node - fixes stackdriver-metadata-agent-cluster-level
- Make alerts dependant on kube-state-metrics …
**Downtime:**
**Testing:**

Fix stackdriver-metadata-agent-cluster-level and reduce alerts

---

shared/versions.yml

Bump exekube in versions.yaml to 0.9.12 - needed to kick off exekube image sync.

GPII-4427 - Bump exekube in version to 0.9.12

---

.circleci/config.yml
.gitlab-ci.yml
common/docker-compose.yaml
common/modules/gcp-project/main.tf
gcp/docker-compose.yaml
gcp/modules/gcp-stackdriver-export/main.tf
shared/versions.yml

This PR adds GCS access logs for GCS buckets.
- Bump exekube to 0.9.12 (Adds access logs support)
- Add GCS access logs for tfstate
- Add GCS access logs for SD exports
**Downtime:**
**Testing:**

GPII-4427 - GCS access logs

---

common/modules/gcp-project/main.tf

This PR should fix missing IAM permission in Staging org:
```
* google_storage_bucket.exported-logs-custom-encryption: googleapi: Error 403: Permission denied on Cloud KMS key. Please ensure that your Cloud Storage service account has been authorized to use this key., forbidden
```
- Add `roles/cloudkms.cryptoKeyEncrypterDecrypter` to projectowner svc account
**Downtime:**
**Testing:**

Fix IAM KMS missing permissions

---

gcp/modules/gke-cluster/main.tf

This PR upgrades K8s/GKE version to 1.15 as it's now the default and GKE version 1.14 will be deprecated in R26 [1].
- Upgrade k8s to 1.15
**Downtime:**
**Testing:**
[1]: https://cloud.google.com/kubernetes-engine/docs/release-notes#coming-soon-20200722

Upgrade K8s to 1.15
